import type { Creature } from '@/models/Creature'
import { Creatures, Spells, Terrains, Towns } from '@/models/enums'

export const creatures: Array<Creature> = [
  {
    name: 'Pikeman',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Castle,
    id: 1,
    minDamage: 1,
    maxDamage: 3,
    health: 10,
    level: 1,
    attack: 4,
    defense: 5,
    hits: 1,
    ranged: false,
    aiValue: 80,
    cost: { gold: 60 },
    fightValue: 1,
    growth: 14,
    speed: 4,
    description: 'Immune to jousting',
    special: {
      immunityToJousting: true,
    },
  },
  {
    name: 'Halberdier',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Castle,
    id: 2,
    minDamage: 2,
    maxDamage: 3,
    health: 10,
    level: 1,
    attack: 6,
    defense: 5,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 115,
    growth: 14,
    cost: { gold: 60 },
    description: 'Immune to jousting',
    special: {
      immunityToJousting: true,
    },
  },
  {
    name: 'Archer',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Castle,
    id: 3,
    minDamage: 2,
    maxDamage: 3,
    health: 10,
    level: 2,
    attack: 6,
    defense: 3,
    hits: 1,
    speed: 4,
    ranged: true,
    description: 'Ranged (12 shots)',
    aiValue: 126,
    growth: 9,
    cost: { gold: 100 },
    special: {
      ranged: true,
    },
  },
  {
    name: 'Marksman',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Castle,
    id: 4,
    minDamage: 2,
    maxDamage: 3,
    health: 10,
    level: 2,
    attack: 6,
    defense: 3,
    hits: 2,
    speed: 6,
    ranged: true,
    special: {
      doubleAttack: true,
      ranged: true,
    },
    description: 'Ranged (24 shots), double attack',
    aiValue: 184,
    growth: 9,
    cost: { gold: 150 },
  },
  {
    name: 'Griffin',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Castle,
    id: 5,
    minDamage: 3,
    maxDamage: 6,
    health: 25,
    level: 3,
    attack: 8,
    defense: 8,
    speed: 6,
    hits: 1,
    ranged: false,
    aiValue: 351,
    growth: 7,
    cost: { gold: 200 },
    special: {
      flying: true,
      twoRetaliations: true,
    },
    description: 'Flying, Two retaliations',
  },
  {
    name: 'Royal Griffin',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Castle,
    id: 6,
    minDamage: 3,
    maxDamage: 6,
    health: 25,
    level: 3,
    attack: 9,
    defense: 9,
    speed: 9,
    hits: 1,
    ranged: false,
    aiValue: 448,
    growth: 7,
    cost: { gold: 240 },
    special: {
      flying: true,
      unlimitedRetaliations: true,
    },
    description: 'Flying, Unlimited retaliations',
  },
  {
    name: 'Swordsman',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Castle,
    id: 7,
    minDamage: 6,
    maxDamage: 9,
    health: 35,
    level: 4,
    attack: 10,
    defense: 12,
    speed: 5,
    hits: 1,
    ranged: false,
    aiValue: 445,
    growth: 4,
    cost: { gold: 300 },
  },
  {
    name: 'Crusader',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Castle,
    id: 8,
    minDamage: 7,
    maxDamage: 10,
    health: 35,
    level: 4,
    attack: 12,
    defense: 12,
    speed: 6,
    hits: 2,
    ranged: false,
    aiValue: 588,
    growth: 4,
    cost: { gold: 400 },
    special: {
      doubleAttack: true,
    },
    description: 'Double attack',
  },
  {
    name: 'Monk',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Castle,
    id: 9,
    minDamage: 10,
    maxDamage: 12,
    health: 30,
    level: 5,
    attack: 12,
    defense: 7,
    speed: 5,
    hits: 1,
    ranged: true,
    aiValue: 485,
    growth: 3,
    cost: { gold: 400 },
    special: {
      ranged: true,
      shots: 12,
    },
    description: 'Ranged (12 shots)',
  },
  {
    name: 'Zealot',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Castle,
    id: 10,
    minDamage: 10,
    maxDamage: 12,
    health: 30,
    level: 5,
    attack: 12,
    defense: 10,
    speed: 7,
    hits: 1,
    ranged: true,
    aiValue: 750,
    growth: 3,
    cost: { gold: 450 },
    special: {
      ranged: true,
      shots: 24,
      noMeleePenalty: true,
    },
    description: 'Ranged (24 shots), No melee penalty',
  },
  {
    name: 'Cavalier',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Castle,
    id: 11,
    minDamage: 15,
    maxDamage: 25,
    health: 100,
    level: 6,
    attack: 15,
    defense: 15,
    hits: 1,
    speed: 7,
    ranged: false,
    aiValue: 1946,
    growth: 2,
    cost: { gold: 1000 },
    special: {
      jousting: true,
    },
    description: 'Jousting',
  },
  {
    name: 'Champion',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Castle,
    id: 12,
    minDamage: 20,
    maxDamage: 25,
    health: 100,
    level: 6,
    attack: 16,
    defense: 16,
    hits: 1,
    speed: 9,
    ranged: false,
    aiValue: 2100,
    growth: 2,
    cost: { gold: 1200 },
    special: {
      jousting: true,
    },
    description: 'Jousting',
  },
  {
    name: 'Angel',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Castle,
    id: 13,
    minDamage: 50,
    maxDamage: 50,
    health: 200,
    level: 7,
    attack: 20,
    defense: 20,
    hits: 1,
    ranged: false,
    speed: 12,
    hates: [83, 84],
    aiValue: 5019,
    growth: 1,
    cost: { gold: 3000, gem: 1 },
    special: {
      flying: true,
      hates: [Creatures.Devil, Creatures.ArchDevil],
      moraleBonusForArmy: 1,
    },
    description: 'Flying, Hates Devils, Morale +1',
  },
  {
    name: 'Archangel',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Castle,
    id: 14,
    minDamage: 50,
    maxDamage: 50,
    health: 250,
    level: 7,
    attack: 30,
    defense: 30,
    hits: 1,
    ranged: false,
    speed: 18,
    hates: [83, 84],
    aiValue: 8776,
    growth: 1,
    cost: { gold: 5000, gem: 3 },
    special: {
      flying: true,
      hates: [Creatures.Devil, Creatures.ArchDevil],
      moraleBonusForArmy: 1,
    },
    description: 'Flying, Hates Devils, Resurrection, Morale +1',
  },
  {
    name: 'Centaur',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Rampart,
    id: 15,
    minDamage: 2,
    maxDamage: 3,
    health: 8,
    level: 1,
    attack: 5,
    defense: 3,
    speed: 6,
    hits: 1,
    ranged: false,
    aiValue: 100,
    growth: 14,
    cost: { gold: 70 },
  },
  {
    name: 'Centaur Captain',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Rampart,
    id: 16,
    minDamage: 2,
    maxDamage: 3,
    health: 10,
    level: 1,
    attack: 6,
    defense: 3,
    hits: 1,
    ranged: false,
    speed: 8,
    aiValue: 138,
    growth: 14,
    cost: { gold: 90 },
  },
  {
    name: 'Dwarf',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Rampart,
    id: 17,
    minDamage: 2,
    maxDamage: 4,
    health: 20,
    level: 2,
    attack: 6,
    defense: 7,
    hits: 1,
    ranged: false,
    speed: 3,
    aiValue: 138,
    growth: 8,
    cost: { gold: 120 },
    special: {
      magicResistanceChance: 20,
    },
    description: 'Magic Resistance 20%',
  },
  {
    name: 'Battle Dwarf',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Rampart,
    id: 18,
    minDamage: 2,
    maxDamage: 4,
    health: 20,
    level: 2,
    attack: 7,
    defense: 7,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 209,
    growth: 8,
    cost: { gold: 150 },
    special: {
      magicResistanceChance: 40,
    },
    description: 'Magic Resistance 40%',
  },
  {
    name: 'Wood Elf',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Rampart,
    id: 19,
    minDamage: 3,
    maxDamage: 5,
    health: 15,
    level: 3,
    attack: 9,
    defense: 5,
    hits: 1,
    ranged: true,
    speed: 6,
    aiValue: 234,
    growth: 7,
    cost: { gold: 200 },
    special: {
      ranged: true,
      shots: 24,
    },
    description: 'Ranged (24 shots)',
  },
  {
    name: 'Grand Elf',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Rampart,
    id: 20,
    minDamage: 3,
    maxDamage: 5,
    health: 15,
    level: 3,
    attack: 9,
    defense: 5,
    hits: 2,
    ranged: true,
    speed: 7,
    aiValue: 331,
    growth: 7,
    cost: { gold: 225 },
    special: {
      doubleAttack: true,
      ranged: true,
      shots: 24,
    },
    description: 'Ranged (24 shots), Double attack',
  },
  {
    name: 'Pegasus',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Rampart,
    id: 21,
    minDamage: 5,
    maxDamage: 9,
    health: 30,
    level: 4,
    attack: 9,
    defense: 8,
    hits: 1,
    ranged: false,
    speed: 8,
    aiValue: 518,
    growth: 5,
    cost: { gold: 250 },
    special: {
      flying: true,
      magicDamperValue: 2,
    },
    description: 'Flying, Magic damper (enemy spells cost two extra spell points)',
  },
  {
    name: 'Silver Pegasus',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Rampart,
    id: 22,
    minDamage: 5,
    maxDamage: 9,
    health: 30,
    level: 4,
    attack: 9,
    defense: 10,
    hits: 1,
    ranged: false,
    speed: 12,
    aiValue: 532,
    growth: 5,
    cost: { gold: 275 },
    special: {
      flying: true,
      magicDamperValue: 2,
    },
    description: 'Flying, Magic damper (enemy spells cost two extra spell points)',
  },
  {
    name: 'Dendroid Guard',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Rampart,
    id: 23,
    minDamage: 10,
    maxDamage: 14,
    health: 55,
    level: 5,
    attack: 9,
    defense: 12,
    hits: 1,
    ranged: false,
    speed: 3,
    aiValue: 517,
    growth: 3,
    cost: { gold: 350 },
    special: {
      binding: true,
    },
    description: 'Binding',
  },
  {
    name: 'Dendroid Soldier',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Rampart,
    id: 24,
    minDamage: 10,
    maxDamage: 14,
    health: 65,
    level: 5,
    attack: 9,
    defense: 12,
    hits: 1,
    ranged: false,
    speed: 4,
    aiValue: 803,
    growth: 3,
    cost: { gold: 425 },
    special: {
      binding: true,
    },
    description: 'Binding',
  },
  {
    name: 'Unicorn',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Rampart,
    id: 25,
    minDamage: 18,
    maxDamage: 22,
    health: 90,
    level: 6,
    attack: 15,
    defense: 14,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 1806,
    growth: 2,
    cost: { gold: 850 },
    special: {
      blindChance: 20,
      auraOfMagicResistanceChance: 20,
    },
    description: 'Blind, Aura of Resistance 20%',
  },
  {
    name: 'War Unicorn',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Rampart,
    id: 26,
    minDamage: 18,
    maxDamage: 22,
    health: 110,
    level: 6,
    attack: 15,
    defense: 14,
    hits: 1,
    ranged: false,
    speed: 9,
    aiValue: 2030,
    growth: 2,
    cost: { gold: 950 },
    special: {
      blindChance: 20,
      auraOfMagicResistanceChance: 20,
    },
    description: 'Blind, Aura of Resistance 20%',
  },
  {
    name: 'Green Dragon',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Rampart,
    id: 27,
    minDamage: 40,
    maxDamage: 50,
    health: 180,
    level: 7,
    attack: 18,
    defense: 18,
    hits: 1,
    ranged: false,
    speed: 10,
    aiValue: 4872,
    growth: 1,
    cost: { gold: 2400, crystal: 1 },
    special: {
      flying: true,
      dragon: true,
      breathAttack: true,
      immunityToSpellLevels: [1, 2, 3],
    },
    description: 'Dragon, Flying, Breath attack, 1-3 level spells immunity',
  },
  {
    name: 'Gold Dragon',
    nativeTerrain: Terrains.Grass,
    townId: Towns.Rampart,
    id: 28,
    minDamage: 40,
    maxDamage: 50,
    health: 250,
    level: 7,
    attack: 27,
    defense: 27,
    hits: 1,
    ranged: false,
    speed: 16,
    aiValue: 8613,
    growth: 1,
    cost: { gold: 4000, crystal: 2 },
    special: {
      flying: true,
      dragon: true,
      breathAttack: true,
      immunityToSpellLevels: [1, 2, 3, 4],
    },
    description: 'Dragon, Flying, Breath attack, 1-4 lvl spells immunity',
  },
  {
    name: 'Gremlin',
    nativeTerrain: Terrains.Snow,
    townId: Towns.Tower,
    id: 29,
    minDamage: 1,
    maxDamage: 2,
    health: 4,
    level: 1,
    attack: 3,
    defense: 3,
    hits: 1,
    ranged: false,
    speed: 4,
    aiValue: 44,
    cost: { gold: 30 },
    growth: 16,
  },
  {
    name: 'Master Gremlin',
    nativeTerrain: Terrains.Snow,
    townId: Towns.Tower,
    id: 30,
    minDamage: 1,
    maxDamage: 2,
    health: 4,
    level: 1,
    attack: 4,
    defense: 4,
    hits: 1,
    ranged: true,
    speed: 5,
    aiValue: 66,
    cost: { gold: 40 },
    growth: 16,
    special: {
      ranged: true,
      shots: 8,
    },
    description: 'Ranged (8 shots)',
  },
  {
    name: 'Stone Gargoyle',
    nativeTerrain: Terrains.Snow,
    townId: Towns.Tower,
    id: 31,
    minDamage: 2,
    maxDamage: 3,
    health: 16,
    level: 2,
    attack: 6,
    defense: 6,
    hits: 1,
    ranged: false,
    speed: 6,
    aiValue: 165,
    cost: { gold: 130 },
    growth: 9,
    special: {
      flying: true,
      nonLiving: true,
    },
    description: 'Unliving, Flying',
  },
  {
    name: 'Obsidian Gargoyle',
    nativeTerrain: Terrains.Snow,
    townId: Towns.Tower,
    id: 32,
    minDamage: 2,
    maxDamage: 3,
    health: 16,
    level: 2,
    attack: 7,
    defense: 7,
    hits: 1,
    ranged: false,
    speed: 9,
    aiValue: 201,
    cost: { gold: 160 },
    growth: 9,
    special: {
      flying: true,
      nonLiving: true,
    },
    description: 'Unliving, Flying',
  },
  {
    name: 'Stone Golem',
    nativeTerrain: Terrains.Snow,
    townId: Towns.Tower,
    id: 33,
    minDamage: 4,
    maxDamage: 5,
    health: 30,
    level: 3,
    attack: 7,
    defense: 10,
    hits: 1,
    ranged: false,
    speed: 3,
    aiValue: 250,
    cost: { gold: 150 },
    growth: 6,
    special: {
      nonLiving: true,
      spellDamageResistance: 50,
    },
    description: 'Unliving, Spell Damage Resistance 50%',
  },
  {
    name: 'Iron Golem',
    nativeTerrain: Terrains.Snow,
    townId: Towns.Tower,
    id: 34,
    minDamage: 4,
    maxDamage: 5,
    health: 35,
    level: 3,
    attack: 9,
    defense: 10,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 412,
    cost: { gold: 200 },
    growth: 6,
    special: {
      nonLiving: true,
      spellDamageResistance: 75,
    },
    description: 'Unliving, Spell Damage Resistance 75%',
  },
  {
    name: 'Mage',
    nativeTerrain: Terrains.Snow,
    townId: Towns.Tower,
    id: 35,
    minDamage: 7,
    maxDamage: 9,
    health: 25,
    level: 4,
    attack: 11,
    defense: 8,
    hits: 1,
    ranged: true,
    speed: 5,
    aiValue: 570,
    cost: { gold: 350 },
    growth: 4,
    special: {
      ranged: true,
      shots: 24,
      noMeleePenalty: true,
      noObstaclePenalty: true,
      reduceCastSpellPointsCount: 2,
    },
    description: 'Ranged (24 shots), No melee penalty, No obstacle penalty, Spells cost -2 spell points',
  },
  {
    name: 'Arch Mage',
    nativeTerrain: Terrains.Snow,
    townId: Towns.Tower,
    id: 36,
    minDamage: 7,
    maxDamage: 9,
    health: 30,
    level: 4,
    attack: 12,
    defense: 9,
    hits: 1,
    ranged: true,
    speed: 7,
    aiValue: 680,
    cost: { gold: 450 },
    growth: 4,
    special: {
      ranged: true,
      shots: 24,
      noMeleePenalty: true,
      noObstaclePenalty: true,
      reduceCastSpellPointsCount: 2,
    },
    description: 'Ranged (24 shots), No melee penalty, No obstacle penalty, Spells cost -2 spell points',
  },
  {
    name: 'Genie',
    nativeTerrain: Terrains.Snow,
    townId: Towns.Tower,
    id: 37,
    minDamage: 13,
    maxDamage: 16,
    health: 40,
    level: 5,
    attack: 12,
    defense: 12,
    hits: 1,
    ranged: false,
    hates: [81, 82],
    speed: 7,
    aiValue: 884,
    cost: { gold: 550 },
    growth: 3,
    special: {
      flying: true,
      hates: [Creatures.Efreet, Creatures.EfreetSultan],
    },
    description: 'Flying, Hates Efreet and Efreet Sultans',
  },
  {
    name: 'Master Genie',
    nativeTerrain: Terrains.Snow,
    townId: Towns.Tower,
    id: 38,
    minDamage: 13,
    maxDamage: 16,
    health: 40,
    level: 5,
    attack: 12,
    defense: 12,
    hits: 1,
    ranged: false,
    hates: [81, 82],
    speed: 11,
    aiValue: 942,
    cost: { gold: 600 },
    growth: 3,
    special: {
      flying: true,
      hates: [Creatures.Efreet, Creatures.EfreetSultan],
    },
    description:
      'Flying, Spellcaster (Bless, Bloodlust, Cure, Haste, Protection from Fire, Protection from Water, Shield, Stone Skin, Fortune, Precision, Protection from Air, Air Shield, Anit-Magic, Protection from Earth, Mirth, Counterstrike, Fire Shield, Frenzy, Prayer, Slayer, Magic Mirror), Hates Efreet and Efreet Sultans',
  },
  {
    name: 'Naga',
    nativeTerrain: Terrains.Snow,
    townId: Towns.Tower,
    id: 39,
    minDamage: 20,
    maxDamage: 20,
    health: 110,
    level: 6,
    attack: 16,
    defense: 13,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 2016,
    cost: { gold: 1100 },
    growth: 2,
    special: {
      noEnemyRetaliation: true,
    },
    description: 'No enemy retaliation',
  },
  {
    name: 'Naga Queen',
    nativeTerrain: Terrains.Snow,
    townId: Towns.Tower,
    id: 40,
    minDamage: 30,
    maxDamage: 30,
    health: 110,
    level: 6,
    attack: 16,
    defense: 13,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 2840,
    cost: { gold: 1600 },
    growth: 2,
    special: {
      noEnemyRetaliation: true,
    },
    description: 'No enemy retaliation',
  },
  {
    name: 'Giant',
    nativeTerrain: Terrains.Snow,
    townId: Towns.Tower,
    id: 41,
    minDamage: 40,
    maxDamage: 60,
    health: 150,
    level: 7,
    attack: 19,
    defense: 16,
    hits: 1,
    ranged: false,
    hates: [70, 71],
    speed: 7,
    aiValue: 3718,
    cost: { gold: 2000, gem: 1 },
    growth: 1,
    special: {
      // immunity: spells.filter((spells) => spells.group?.indexOf('mind') !== -1),
    },
    description: 'Immunity to Mind spells',
  },
  {
    name: 'Titan',
    nativeTerrain: Terrains.Snow,
    townId: Towns.Tower,
    id: 42,
    minDamage: 40,
    maxDamage: 60,
    health: 300,
    level: 7,
    attack: 24,
    defense: 24,
    hits: 1,
    ranged: true,
    hates: [70, 71],
    speed: 11,
    aiValue: 7500,
    cost: { gold: 5000, gem: 2 },
    growth: 1,
    special: {
      ranged: true,
      shots: 24,
      noMeleePenalty: true,
      hates: [Creatures.BlackDragon],
      // immunity: spells.filter((spells) => spells.group?.indexOf('mind') !== -1),
    },
    description: 'Ranged (24 shots), No melee penalty, Immunity to Mind spells, Hates Black Dragons',
  },
  {
    name: 'Skeleton',
    nativeTerrain: Terrains.Dirt,
    townId: Towns.Necropolis,
    id: 43,
    minDamage: 1,
    maxDamage: 3,
    health: 6,
    level: 1,
    attack: 5,
    defense: 4,
    hits: 1,
    ranged: false,
    speed: 4,
    aiValue: 60,
    cost: { gold: 60 },
    growth: 12,
    special: {
      undead: true,
    },
    description: 'Undead',
  },
  {
    name: 'Skeleton Warrior',
    nativeTerrain: Terrains.Dirt,
    townId: Towns.Necropolis,
    id: 44,
    minDamage: 1,
    maxDamage: 3,
    health: 6,
    level: 1,
    attack: 6,
    defense: 6,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 85,
    cost: { gold: 70 },
    growth: 12,
    special: {
      undead: true,
    },
    description: 'Undead',
  },
  {
    name: 'Walking Dead',
    nativeTerrain: Terrains.Dirt,
    townId: Towns.Necropolis,
    id: 45,
    minDamage: 2,
    maxDamage: 3,
    health: 15,
    level: 2,
    attack: 5,
    defense: 5,
    hits: 1,
    ranged: false,
    speed: 3,
    aiValue: 98,
    cost: { gold: 100 },
    growth: 8,
    special: {
      undead: true,
    },
    description: 'Undead',
  },
  {
    name: 'Zombie',
    nativeTerrain: Terrains.Dirt,
    townId: Towns.Necropolis,
    id: 46,
    minDamage: 2,
    maxDamage: 3,
    health: 20,
    level: 2,
    attack: 5,
    defense: 5,
    hits: 1,
    ranged: false,
    speed: 4,
    aiValue: 128,
    cost: { gold: 125 },
    growth: 8,
    special: {
      undead: true,
    },
    description: 'Undead, Disease',
  },
  {
    name: 'Wight',
    nativeTerrain: Terrains.Dirt,
    townId: Towns.Necropolis,
    id: 47,
    minDamage: 3,
    maxDamage: 5,
    health: 18,
    level: 3,
    attack: 7,
    defense: 7,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 252,
    cost: { gold: 200 },
    growth: 7,
    special: {
      undead: true,
      flying: true,
    },
    description: 'Undead, Flying, Regeneration',
  },
  {
    name: 'Wraith',
    nativeTerrain: Terrains.Dirt,
    townId: Towns.Necropolis,
    id: 48,
    minDamage: 3,
    maxDamage: 5,
    health: 18,
    level: 3,
    attack: 7,
    defense: 7,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 315,
    cost: { gold: 230 },
    growth: 7,
    special: {
      undead: true,
      flying: true,
    },
    description: 'Undead, Flying, Regeneration, Mana drain',
  },
  {
    name: 'Vampire',
    nativeTerrain: Terrains.Dirt,
    townId: Towns.Necropolis,
    id: 49,
    minDamage: 5,
    maxDamage: 8,
    health: 30,
    level: 4,
    attack: 10,
    defense: 9,
    hits: 1,
    ranged: false,
    speed: 6,
    aiValue: 555,
    cost: { gold: 360 },
    growth: 4,
    special: {
      undead: true,
      flying: true,
      noEnemyRetaliation: true,
    },
    description: 'Undead, Flying, No enemy retaliation',
  },
  {
    name: 'Vampire Lord',
    nativeTerrain: Terrains.Dirt,
    townId: Towns.Necropolis,
    id: 50,
    minDamage: 5,
    maxDamage: 8,
    health: 40,
    level: 4,
    attack: 10,
    defense: 10,
    hits: 1,
    ranged: false,
    speed: 9,
    aiValue: 783,
    cost: { gold: 500 },
    growth: 4,
    special: {
      undead: true,
      flying: true,
      noEnemyRetaliation: true,
      lifeDrain: true,
    },
    description: 'Undead, Flying, No enemy retaliation, Life drain',
  },
  {
    name: 'Lich',
    nativeTerrain: Terrains.Dirt,
    townId: Towns.Necropolis,
    id: 51,
    minDamage: 11,
    maxDamage: 13,
    health: 30,
    level: 5,
    attack: 13,
    defense: 10,
    hits: 1,
    ranged: true,
    speed: 6,
    aiValue: 848,
    cost: { gold: 550 },
    growth: 3,
    special: {
      ranged: true,
      shots: 12,
      undead: true,
    },
    description: 'Ranged (12 shots), Undead, Death cloud',
  },
  {
    name: 'Power Lich',
    nativeTerrain: Terrains.Dirt,
    townId: Towns.Necropolis,
    id: 52,
    minDamage: 11,
    maxDamage: 15,
    health: 40,
    level: 5,
    attack: 13,
    defense: 10,
    hits: 1,
    ranged: true,
    speed: 7,
    aiValue: 1079,
    cost: { gold: 600 },
    growth: 3,
    special: {
      ranged: true,
      shots: 24,
      undead: true,
    },
    description: 'Ranged (24 shots), Undead, Death cloud',
  },
  {
    name: 'Black Knight',
    nativeTerrain: Terrains.Dirt,
    townId: Towns.Necropolis,
    id: 53,
    minDamage: 15,
    maxDamage: 30,
    health: 120,
    level: 6,
    attack: 16,
    defense: 16,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 2087,
    cost: { gold: 1200 },
    growth: 2,
    special: {
      undead: true,
    },
    description: 'Undead, Curse',
  },
  {
    name: 'Dread Knight',
    nativeTerrain: Terrains.Dirt,
    townId: Towns.Necropolis,
    id: 54,
    minDamage: 15,
    maxDamage: 30,
    health: 120,
    level: 6,
    attack: 18,
    defense: 18,
    hits: 1,
    ranged: false,
    speed: 9,
    aiValue: 2382,
    cost: { gold: 1500 },
    growth: 2,
    special: {
      undead: true,
    },
    description: 'Undead, Curse, Death blow',
  },
  {
    name: 'Bone Dragon',
    nativeTerrain: Terrains.Dirt,
    townId: Towns.Necropolis,
    id: 55,
    minDamage: 25,
    maxDamage: 50,
    health: 150,
    level: 7,
    attack: 17,
    defense: 15,
    hits: 1,
    ranged: false,
    speed: 9,
    aiValue: 3388,
    cost: { gold: 1800 },
    growth: 1,
    special: {
      dragon: true,
      undead: true,
      flying: true,
    },
    description: 'Dragon, Undead, Flying, Morale -1',
  },
  {
    name: 'Ghost Dragon',
    nativeTerrain: Terrains.Dirt,
    townId: Towns.Necropolis,
    id: 56,
    minDamage: 25,
    maxDamage: 50,
    health: 200,
    level: 7,
    attack: 19,
    defense: 17,
    hits: 1,
    ranged: false,
    speed: 14,
    aiValue: 4696,
    cost: { gold: 3000, mercury: 1 },
    growth: 1,
    special: {
      dragon: true,
      undead: true,
      flying: true,
      moralePenaltyForEnemyArmy: -1,
    },
    description: 'Dragon, Undead, Flying, Morale -1, Aging',
  },
  {
    name: 'Troglodyte',
    nativeTerrain: Terrains.Subterranean,
    townId: Towns.Dungeon,
    id: 57,
    minDamage: 1,
    maxDamage: 3,
    health: 5,
    level: 1,
    attack: 4,
    defense: 3,
    hits: 1,
    ranged: false,
    speed: 4,
    aiValue: 59,
    cost: { gold: 50 },
    growth: 14,
    description: 'Immune to Blinding',
  },
  {
    name: 'Infernal Troglodyte',
    nativeTerrain: Terrains.Subterranean,
    townId: Towns.Dungeon,
    id: 58,
    minDamage: 1,
    maxDamage: 3,
    health: 6,
    level: 1,
    attack: 5,
    defense: 4,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 84,
    cost: { gold: 65 },
    growth: 14,
    description: 'Immune to Blinding',
  },
  {
    name: 'Harpy',
    nativeTerrain: Terrains.Subterranean,
    townId: Towns.Dungeon,
    id: 59,
    minDamage: 1,
    maxDamage: 4,
    health: 14,
    level: 2,
    attack: 6,
    defense: 5,
    hits: 1,
    ranged: false,
    speed: 6,
    aiValue: 154,
    cost: { gold: 130 },
    growth: 8,
    special: {
      flying: true,
    },
    description: 'Flying, Strike and return',
  },
  {
    name: 'Harpy Hag',
    nativeTerrain: Terrains.Subterranean,
    townId: Towns.Dungeon,
    id: 60,
    minDamage: 1,
    maxDamage: 4,
    health: 14,
    level: 2,
    attack: 6,
    defense: 6,
    hits: 1,
    ranged: false,
    speed: 9,
    aiValue: 238,
    cost: { gold: 170 },
    growth: 8,
    special: {
      flying: true,
      noEnemyRetaliation: true,
    },
    description: 'Flying, Strike and return, No enemy retaliation',
  },
  {
    name: 'Beholder',
    nativeTerrain: Terrains.Subterranean,
    townId: Towns.Dungeon,
    id: 61,
    minDamage: 3,
    maxDamage: 5,
    health: 22,
    level: 3,
    attack: 9,
    defense: 7,
    hits: 1,
    ranged: true,
    speed: 5,
    aiValue: 336,
    cost: { gold: 250 },
    growth: 7,
    special: {
      noMeleePenalty: true,
      ranged: true,
      shots: 12,
    },
    description: 'Ranged (12 shots), No melee penalty',
  },
  {
    name: 'Evil Eye',
    nativeTerrain: Terrains.Subterranean,
    townId: Towns.Dungeon,
    id: 62,
    minDamage: 3,
    maxDamage: 5,
    health: 22,
    level: 3,
    attack: 10,
    defense: 8,
    hits: 1,
    ranged: true,
    speed: 7,
    aiValue: 367,
    cost: { gold: 280 },
    growth: 7,
    special: {
      noMeleePenalty: true,
      ranged: true,
      shots: 24,
    },
    description: 'Ranged (24 shots), No melee penalty',
  },
  {
    name: 'Medusa',
    nativeTerrain: Terrains.Subterranean,
    townId: Towns.Dungeon,
    id: 63,
    minDamage: 6,
    maxDamage: 8,
    health: 25,
    level: 4,
    attack: 9,
    defense: 9,
    hits: 1,
    ranged: true,
    speed: 5,
    aiValue: 517,
    cost: { gold: 300 },
    growth: 4,
    special: {
      noMeleePenalty: true,
      ranged: true,
      shots: 4,
      petrify: true,
    },
    description: 'Ranged (4 shots), No melee penalty, Petrify',
  },
  {
    name: 'Medusa Queen',
    nativeTerrain: Terrains.Subterranean,
    townId: Towns.Dungeon,
    id: 64,
    minDamage: 6,
    maxDamage: 8,
    health: 30,
    level: 4,
    attack: 10,
    defense: 10,
    hits: 1,
    ranged: true,
    speed: 6,
    aiValue: 577,
    cost: { gold: 330 },
    growth: 4,
    special: {
      noMeleePenalty: true,
      ranged: true,
      shots: 8,
      petrify: true,
    },
    description: 'Ranged (8 shots), No melee penalty, Petrify',
  },
  {
    name: 'Minotaur',
    nativeTerrain: Terrains.Subterranean,
    townId: Towns.Dungeon,
    id: 65,
    minDamage: 12,
    maxDamage: 20,
    health: 50,
    level: 5,
    attack: 14,
    defense: 12,
    hits: 1,
    ranged: false,
    speed: 6,
    aiValue: 835,
    cost: { gold: 500 },
    growth: 3,
    description: 'Positive Morale',
  },
  {
    name: 'Minotaur King',
    nativeTerrain: Terrains.Subterranean,
    townId: Towns.Dungeon,
    id: 66,
    minDamage: 12,
    maxDamage: 20,
    health: 50,
    level: 5,
    attack: 15,
    defense: 15,
    hits: 1,
    ranged: false,
    speed: 8,
    aiValue: 1068,
    cost: { gold: 575 },
    growth: 3,
    description: 'Positive Morale',
  },
  {
    name: 'Manticore',
    nativeTerrain: Terrains.Subterranean,
    townId: Towns.Dungeon,
    id: 67,
    minDamage: 14,
    maxDamage: 20,
    health: 80,
    level: 6,
    attack: 15,
    defense: 13,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 1547,
    cost: { gold: 850 },
    growth: 2,
    special: {
      flying: true,
    },
    description: 'Flying',
  },
  {
    name: 'Scorpicore',
    nativeTerrain: Terrains.Subterranean,
    townId: Towns.Dungeon,
    id: 68,
    minDamage: 14,
    maxDamage: 20,
    health: 80,
    level: 6,
    attack: 16,
    defense: 14,
    hits: 1,
    ranged: false,
    speed: 11,
    aiValue: 1589,
    cost: { gold: 1050 },
    growth: 2,
    special: {
      flying: true,
    },
    description: 'Flying, Paralyze',
  },
  {
    name: 'Red Dragon',
    nativeTerrain: Terrains.Subterranean,
    townId: Towns.Dungeon,
    id: 69,
    minDamage: 40,
    maxDamage: 50,
    health: 180,
    level: 7,
    attack: 19,
    defense: 19,
    hits: 1,
    ranged: false,
    speed: 11,
    aiValue: 4702,
    cost: { gold: 2500, sulfur: 1 },
    growth: 1,
    special: {
      flying: true,
      immunityToSpellLevels: [1, 2, 3],
    },
    description: 'Dragon, Flying, Breath attack, 1-3 level spells immunity',
  },
  {
    name: 'Black Dragon',
    nativeTerrain: Terrains.Subterranean,
    townId: Towns.Dungeon,
    id: 70,
    minDamage: 40,
    maxDamage: 50,
    health: 300,
    level: 7,
    attack: 25,
    defense: 25,
    hits: 1,
    ranged: false,
    hates: [41, 42],
    speed: 15,
    aiValue: 8721,
    cost: { gold: 4000, sulfur: 2 },
    growth: 1,
    special: {
      flying: true,
      immunityToSpellLevels: [1, 2, 3, 4, 5],
    },
    description: 'Dragon, Flying, Breath attack, Magic immunity, Hates Titans',
  },
  {
    name: 'Imp',
    nativeTerrain: Terrains.Lava,
    townId: Towns.Inferno,
    id: 71,
    minDamage: 1,
    maxDamage: 2,
    health: 4,
    level: 1,
    attack: 2,
    defense: 3,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 50,
    cost: { gold: 50 },
    growth: 15,
  },
  {
    name: 'Familiar',
    nativeTerrain: Terrains.Lava,
    townId: Towns.Inferno,
    id: 72,
    minDamage: 1,
    maxDamage: 2,
    health: 4,
    level: 1,
    attack: 4,
    defense: 4,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 60,
    cost: { gold: 60 },
    growth: 15,
    description: 'Magic channel',
  },
  {
    name: 'Gog',
    nativeTerrain: Terrains.Lava,
    townId: Towns.Inferno,
    id: 73,
    minDamage: 2,
    maxDamage: 4,
    health: 13,
    level: 2,
    attack: 6,
    defense: 4,
    hits: 1,
    ranged: true,
    speed: 4,
    aiValue: 159,
    cost: { gold: 125 },
    growth: 8,
    description: 'Ranged (12 shots)',
  },
  {
    name: 'Magog',
    nativeTerrain: Terrains.Lava,
    townId: Towns.Inferno,
    id: 74,
    minDamage: 2,
    maxDamage: 4,
    health: 13,
    level: 2,
    attack: 7,
    defense: 4,
    hits: 1,
    ranged: true,
    speed: 6,
    aiValue: 240,
    cost: { gold: 175 },
    growth: 8,
    description: 'Ranged (24 shots), Fireball attack',
  },
  {
    name: 'Hell Hound',
    nativeTerrain: Terrains.Lava,
    townId: Towns.Inferno,
    id: 75,
    minDamage: 2,
    maxDamage: 7,
    health: 25,
    level: 3,
    attack: 10,
    defense: 6,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 357,
    cost: { gold: 200 },
    growth: 5,
  },
  {
    name: 'Cerberus',
    nativeTerrain: Terrains.Lava,
    townId: Towns.Inferno,
    id: 76,
    minDamage: 2,
    maxDamage: 7,
    health: 25,
    level: 3,
    attack: 10,
    defense: 8,
    hits: 1,
    ranged: false,
    speed: 8,
    aiValue: 392,
    cost: { gold: 250 },
    growth: 5,
    special: {
      noEnemyRetaliation: true,
    },
    description: 'No enemy retaliation, 3-headed attack',
  },
  {
    name: 'Demon',
    nativeTerrain: Terrains.Lava,
    townId: Towns.Inferno,
    id: 77,
    minDamage: 7,
    maxDamage: 9,
    health: 35,
    level: 4,
    attack: 10,
    defense: 10,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 445,
    cost: { gold: 250 },
    growth: 4,
  },
  {
    name: 'Horned Demon',
    nativeTerrain: Terrains.Lava,
    townId: Towns.Inferno,
    id: 78,
    minDamage: 7,
    maxDamage: 9,
    health: 40,
    level: 4,
    attack: 10,
    defense: 10,
    hits: 1,
    ranged: false,
    speed: 6,
    aiValue: 480,
    cost: { gold: 270 },
    growth: 4,
  },
  {
    name: 'Pit Fiend',
    nativeTerrain: Terrains.Lava,
    townId: Towns.Inferno,
    id: 79,
    minDamage: 13,
    maxDamage: 17,
    health: 45,
    level: 5,
    attack: 13,
    defense: 13,
    hits: 1,
    ranged: false,
    speed: 6,
    aiValue: 765,
    cost: { gold: 500 },
    growth: 3,
  },
  {
    name: 'Pit Lord',
    nativeTerrain: Terrains.Lava,
    townId: Towns.Inferno,
    id: 80,
    minDamage: 13,
    maxDamage: 17,
    health: 45,
    level: 5,
    attack: 13,
    defense: 13,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 1224,
    cost: { gold: 700 },
    growth: 3,
    description: 'Summon demons',
  },
  {
    name: 'Efreet',
    nativeTerrain: Terrains.Lava,
    townId: Towns.Inferno,
    id: 81,
    minDamage: 16,
    maxDamage: 24,
    health: 90,
    level: 6,
    attack: 16,
    defense: 12,
    hits: 1,
    ranged: false,
    hates: [37, 38],
    speed: 9,
    aiValue: 1670,
    cost: { gold: 900 },
    growth: 2,
    special: {
      flying: true,
      hates: [Creatures.Genie, Creatures.MasterGenie],
      immunityToSpellElement: ['fire'],
      immunity: [Spells.MagicArrow],
    },
    description: 'Flying, Fire immunity, Hates Genies',
  },
  {
    name: 'Efreet Sultan',
    nativeTerrain: Terrains.Lava,
    townId: Towns.Inferno,
    id: 82,
    minDamage: 16,
    maxDamage: 24,
    health: 90,
    level: 6,
    attack: 16,
    defense: 14,
    hits: 1,
    ranged: false,
    hates: [37, 38],
    speed: 13,
    aiValue: 2343,
    cost: { gold: 1100 },
    growth: 2,
    special: {
      flying: true,
      hates: [Creatures.Genie, Creatures.MasterGenie],
      immunityToSpellElement: ['fire'],
      immunity: [Spells.MagicArrow],
    },
    description: 'Flying, Fire shield, Fire immunity, Hates Genies',
  },
  {
    name: 'Devil',
    nativeTerrain: Terrains.Lava,
    townId: Towns.Inferno,
    id: 83,
    minDamage: 30,
    maxDamage: 40,
    health: 160,
    level: 7,
    attack: 19,
    defense: 21,
    hits: 1,
    ranged: false,
    hates: [13, 14],
    speed: 11,
    aiValue: 5101,
    cost: { gold: 2700, mercury: 1 },
    growth: 1,
    special: {
      flying: true,
      noEnemyRetaliation: true,
      hates: [Creatures.Angel, Creatures.Archangel],
    },
    description: 'Teleporting, No enemy retaliation, Luck -1, Hates Angels',
  },
  {
    name: 'Arch Devil',
    nativeTerrain: Terrains.Lava,
    townId: Towns.Inferno,
    id: 84,
    minDamage: 30,
    maxDamage: 40,
    health: 200,
    level: 7,
    attack: 26,
    defense: 28,
    hits: 1,
    ranged: false,
    hates: [13, 14],
    speed: 17,
    aiValue: 7115,
    cost: { gold: 4500, mercury: 2 },
    growth: 1,
    special: {
      flying: true,
      noEnemyRetaliation: true,
      hates: [Creatures.Angel, Creatures.Archangel],
    },
    description: 'Teleporting, No enemy retaliation, Luck -2, Hates Angels',
  },
  {
    name: 'Gnoll',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Fortress,
    id: 85,
    minDamage: 2,
    maxDamage: 3,
    health: 6,
    level: 1,
    attack: 3,
    defense: 5,
    hits: 1,
    ranged: false,
    speed: 4,
    aiValue: 56,
    cost: { gold: 50 },
    growth: 12,
  },
  {
    name: 'Gnoll Marauder',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Fortress,
    id: 86,
    minDamage: 2,
    maxDamage: 3,
    health: 6,
    level: 1,
    attack: 4,
    defense: 6,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 90,
    cost: { gold: 70 },
    growth: 12,
  },
  {
    name: 'Lizardman',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Fortress,
    id: 87,
    minDamage: 2,
    maxDamage: 3,
    health: 14,
    level: 2,
    attack: 5,
    defense: 6,
    hits: 1,
    ranged: true,
    speed: 4,
    aiValue: 151,
    cost: { gold: 110 },
    growth: 9,
    description: 'Ranged (12 shots)',
  },
  {
    name: 'Lizard Warrior',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Fortress,
    id: 88,
    minDamage: 2,
    maxDamage: 5,
    health: 15,
    level: 2,
    attack: 6,
    defense: 8,
    hits: 1,
    ranged: true,
    speed: 5,
    aiValue: 209,
    cost: { gold: 140 },
    growth: 9,
    description: 'Ranged (24 shots)',
  },
  {
    name: 'Serpent Fly',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Fortress,
    id: 89,
    minDamage: 2,
    maxDamage: 5,
    health: 20,
    level: 3,
    attack: 7,
    defense: 9,
    hits: 1,
    ranged: false,
    speed: 9,
    aiValue: 268,
    cost: { gold: 220 },
    growth: 8,
    special: {
      flying: true,
    },
    description: 'Flying, Dispel',
  },
  {
    name: 'Dragon Fly',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Fortress,
    id: 90,
    minDamage: 2,
    maxDamage: 5,
    health: 20,
    level: 3,
    attack: 8,
    defense: 10,
    hits: 1,
    ranged: false,
    speed: 13,
    aiValue: 312,
    cost: { gold: 240 },
    growth: 8,
    special: {
      flying: true,
    },
    description: 'Flying, Dispel, Weakness',
  },
  {
    name: 'Basilisk',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Fortress,
    id: 91,
    minDamage: 6,
    maxDamage: 10,
    health: 35,
    level: 4,
    attack: 11,
    defense: 11,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 552,
    cost: { gold: 325 },
    growth: 4,
    special: {
      petrify: true,
    },
    description: 'Petrify',
  },
  {
    name: 'Greater Basilisk',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Fortress,
    id: 92,
    minDamage: 6,
    maxDamage: 10,
    health: 40,
    level: 4,
    attack: 12,
    defense: 12,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 714,
    cost: { gold: 400 },
    growth: 4,
    special: {
      petrify: true,
    },
    description: 'Petrify',
  },
  {
    name: 'Gorgon',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Fortress,
    id: 93,
    minDamage: 12,
    maxDamage: 16,
    health: 70,
    level: 5,
    attack: 10,
    defense: 14,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 890,
    cost: { gold: 525 },
    growth: 3,
  },
  {
    name: 'Mighty Gorgon',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Fortress,
    id: 94,
    minDamage: 12,
    maxDamage: 16,
    health: 70,
    level: 5,
    attack: 11,
    defense: 16,
    hits: 1,
    ranged: false,
    speed: 6,
    aiValue: 1028,
    cost: { gold: 600 },
    growth: 3,
    special: {
      baseDeathStareChance: 10,
    },
    description: 'Death stare 10% chance/unit',
  },
  {
    name: 'Wyvern',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Fortress,
    id: 95,
    minDamage: 14,
    maxDamage: 18,
    health: 70,
    level: 6,
    attack: 14,
    defense: 14,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 1350,
    cost: { gold: 800 },
    growth: 2,
    special: {
      flying: true,
    },
    description: 'Flying',
  },
  {
    name: 'Wyvern Monarch',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Fortress,
    id: 96,
    minDamage: 18,
    maxDamage: 22,
    health: 70,
    level: 6,
    attack: 14,
    defense: 14,
    hits: 1,
    ranged: false,
    speed: 11,
    aiValue: 1518,
    cost: { gold: 1100 },
    growth: 2,
    special: {
      flying: true,
      poisonChance: 30,
    },
    description: 'Flying, Poison',
  },
  {
    name: 'Hydra',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Fortress,
    id: 97,
    minDamage: 25,
    maxDamage: 45,
    health: 175,
    level: 7,
    attack: 16,
    defense: 18,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 4120,
    cost: { gold: 2200 },
    growth: 1,
    special: {
      noEnemyRetaliation: true,
    },
    description: 'No enemy retaliation, Attack all adjacent enemies',
  },
  {
    name: 'Chaos Hydra',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Fortress,
    id: 98,
    minDamage: 25,
    maxDamage: 45,
    health: 250,
    level: 7,
    attack: 18,
    defense: 20,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 5931,
    cost: { gold: 3500, sulfur: 1 },
    growth: 1,
    special: {
      noEnemyRetaliation: true,
    },
    description: 'No enemy retaliation, Attack all adjacent enemies',
  },
  {
    name: 'Goblin',
    nativeTerrain: Terrains.Rough,
    townId: Towns.Stronghold,
    id: 99,
    minDamage: 1,
    maxDamage: 2,
    health: 5,
    level: 1,
    attack: 4,
    defense: 2,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 60,
    cost: { gold: 40 },
    growth: 15,
  },
  {
    name: 'Hobgoblin',
    nativeTerrain: Terrains.Rough,
    townId: Towns.Stronghold,
    id: 100,
    minDamage: 1,
    maxDamage: 2,
    health: 5,
    level: 1,
    attack: 5,
    defense: 3,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 78,
    cost: { gold: 50 },
    growth: 15,
  },
  {
    name: 'Wolf Rider',
    nativeTerrain: Terrains.Rough,
    townId: Towns.Stronghold,
    id: 101,
    minDamage: 2,
    maxDamage: 4,
    health: 10,
    level: 2,
    attack: 7,
    defense: 5,
    hits: 1,
    ranged: false,
    speed: 6,
    aiValue: 130,
    cost: { gold: 100 },
    growth: 9,
  },
  {
    name: 'Wolf Raider',
    nativeTerrain: Terrains.Rough,
    townId: Towns.Stronghold,
    id: 102,
    minDamage: 3,
    maxDamage: 4,
    health: 10,
    level: 2,
    attack: 8,
    defense: 5,
    hits: 2,
    ranged: false,
    speed: 8,
    aiValue: 203,
    cost: { gold: 140 },
    growth: 9,
    special: {
      doubleAttack: true,
    },
    description: 'Double attack',
  },
  {
    name: 'Orc',
    nativeTerrain: Terrains.Rough,
    townId: Towns.Stronghold,
    id: 103,
    minDamage: 2,
    maxDamage: 5,
    health: 15,
    level: 3,
    attack: 8,
    defense: 4,
    hits: 1,
    ranged: true,
    speed: 4,
    aiValue: 192,
    cost: { gold: 150 },
    growth: 7,
    description: 'Ranged (12 shots)',
  },
  {
    name: 'Orc Chieftain',
    nativeTerrain: Terrains.Rough,
    townId: Towns.Stronghold,
    id: 104,
    minDamage: 2,
    maxDamage: 5,
    health: 20,
    level: 3,
    attack: 8,
    defense: 4,
    hits: 1,
    ranged: true,
    speed: 5,
    aiValue: 240,
    cost: { gold: 165 },
    growth: 7,
    description: 'Ranged (24 shots)',
  },
  {
    name: 'Ogre',
    nativeTerrain: Terrains.Rough,
    townId: Towns.Stronghold,
    id: 105,
    minDamage: 6,
    maxDamage: 12,
    health: 40,
    level: 4,
    attack: 13,
    defense: 7,
    hits: 1,
    ranged: false,
    speed: 4,
    aiValue: 416,
    cost: { gold: 300 },
    growth: 4,
  },
  {
    name: 'Ogre Mage',
    nativeTerrain: Terrains.Rough,
    townId: Towns.Stronghold,
    id: 106,
    minDamage: 6,
    maxDamage: 12,
    health: 60,
    level: 4,
    attack: 13,
    defense: 7,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 672,
    cost: { gold: 400 },
    growth: 4,
    description: 'Cast Bloodlust x3',
  },
  {
    name: 'Roc',
    nativeTerrain: Terrains.Rough,
    townId: Towns.Stronghold,
    id: 107,
    minDamage: 11,
    maxDamage: 15,
    health: 60,
    level: 5,
    attack: 13,
    defense: 11,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 1027,
    cost: { gold: 600 },
    growth: 3,
    special: {
      flying: true,
    },
    description: 'Flying',
  },
  {
    name: 'Thunderbird',
    nativeTerrain: Terrains.Rough,
    townId: Towns.Stronghold,
    id: 108,
    minDamage: 11,
    maxDamage: 15,
    health: 60,
    level: 5,
    attack: 13,
    defense: 11,
    hits: 1,
    ranged: false,
    speed: 11,
    aiValue: 1106,
    cost: { gold: 700 },
    growth: 3,
    special: {
      flying: true,
      lightningStrikeChance: 20,
    },
    description: 'Flying, Lightning strike',
  },
  {
    name: 'Cyclops',
    nativeTerrain: Terrains.Rough,
    townId: Towns.Stronghold,
    id: 109,
    minDamage: 16,
    maxDamage: 20,
    health: 70,
    level: 6,
    attack: 15,
    defense: 12,
    hits: 1,
    ranged: true,
    speed: 6,
    aiValue: 1266,
    cost: { gold: 750 },
    growth: 2,
    description: 'Ranged (16 shots), Can attack siege walls',
  },
  {
    name: 'Cyclops King',
    nativeTerrain: Terrains.Rough,
    townId: Towns.Stronghold,
    id: 110,
    minDamage: 16,
    maxDamage: 20,
    health: 70,
    level: 6,
    attack: 17,
    defense: 13,
    hits: 1,
    ranged: true,
    speed: 8,
    aiValue: 1443,
    cost: { gold: 1100 },
    growth: 2,
    description: 'Ranged (24 shots), Can attack siege walls',
  },
  {
    name: 'Behemoth',
    nativeTerrain: Terrains.Rough,
    townId: Towns.Stronghold,
    id: 111,
    minDamage: 30,
    maxDamage: 50,
    health: 160,
    level: 7,
    attack: 17,
    defense: 17,
    hits: 1,
    ranged: false,
    speed: 6,
    aiValue: 3162,
    cost: { gold: 1500 },
    growth: 1,
    special: {
      ignoreEmenyDefencePercents: 40,
    },
    description: 'Defense -40% to enemy target',
  },
  {
    name: 'Ancient Behemoth',
    nativeTerrain: Terrains.Rough,
    townId: Towns.Stronghold,
    id: 112,
    minDamage: 30,
    maxDamage: 50,
    health: 300,
    level: 7,
    attack: 19,
    defense: 19,
    hits: 1,
    ranged: false,
    speed: 9,
    aiValue: 6168,
    cost: { gold: 3000, crystal: 1 },
    growth: 1,
    special: {
      ignoreEmenyDefencePercents: 80,
    },
    description: 'Defense -80% to enemy target',
  },
  {
    name: 'Pixie',
    nativeTerrain: Terrains.Hightlands,
    townId: Towns.Conflux,
    id: 113,
    minDamage: 1,
    maxDamage: 2,
    health: 3,
    level: 1,
    attack: 2,
    defense: 2,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 55,
    cost: { gold: 25 },
    growth: 20,
    special: {
      flying: true,
    },
    description: 'Flying',
  },
  {
    name: 'Sprite',
    nativeTerrain: Terrains.Hightlands,
    townId: Towns.Conflux,
    id: 114,
    minDamage: 1,
    maxDamage: 3,
    health: 3,
    level: 1,
    attack: 2,
    defense: 2,
    hits: 1,
    ranged: false,
    speed: 9,
    aiValue: 95,
    cost: { gold: 30 },
    growth: 20,
    special: {
      flying: true,
      noEnemyRetaliation: true,
    },
    description: 'Flying, No enemy retaliation',
  },
  {
    name: 'Air Elemental',
    nativeTerrain: Terrains.Hightlands,
    townId: Towns.Conflux,
    id: 115,
    minDamage: 2,
    maxDamage: 8,
    health: 25,
    level: 2,
    attack: 9,
    defense: 9,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 356,
    cost: { gold: 250 },
    growth: 6,
    special: {
      nonLiving: true,
      immunity: [Spells.MeteorShower],
      vulnerablesToSpells: [Spells.Armageddon, Spells.LightningBolt, Spells.ChainLightning, Spells.TitansLightningBolt],
    },
    description:
      'Elemental, Lightning and Armageddon vulnerability, Immune to Meteor Shower, +100% to basic damage to Earth and Magma Elementals',
  },
  {
    name: 'Storm Elemental',
    nativeTerrain: Terrains.Hightlands,
    townId: Towns.Conflux,
    id: 116,
    minDamage: 2,
    maxDamage: 8,
    health: 25,
    level: 2,
    attack: 9,
    defense: 9,
    hits: 1,
    ranged: true,
    speed: 8,
    aiValue: 486,
    cost: { gold: 275 },
    growth: 6,
    special: {
      nonLiving: true,
      immunity: [Spells.MeteorShower],
      vulnerablesToSpells: [Spells.Armageddon, Spells.LightningBolt, Spells.ChainLightning, Spells.TitansLightningBolt],
    },
    description:
      'Ranged (24 shots), Elemental, Lightning and Armageddon vulnerability, Immune to Meteor Shower, +100% to basic damage to Earth and Magma Elementals, Casts Protection from Air',
  },
  {
    name: 'Water Elemental',
    nativeTerrain: Terrains.Hightlands,
    townId: Towns.Conflux,
    id: 117,
    minDamage: 3,
    maxDamage: 7,
    health: 30,
    level: 3,
    attack: 8,
    defense: 10,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 315,
    cost: { gold: 300 },
    growth: 6,
    special: {
      nonLiving: true,
      vulnerablesToSpells: [Spells.Armageddon, Spells.Fireball, Spells.Inferno],
      immunity: [Spells.IceBolt, Spells.FrostRing],
    },
    description:
      'Elemental, Ice immunity, Vulnerable to Fireball, Inferno and Armageddon, +100% to basic damage to Fire and Energy Elementals',
  },
  {
    name: 'Ice Elemental',
    nativeTerrain: Terrains.Hightlands,
    townId: Towns.Conflux,
    id: 118,
    minDamage: 3,
    maxDamage: 7,
    health: 30,
    level: 3,
    attack: 8,
    defense: 10,
    hits: 1,
    ranged: true,
    speed: 6,
    aiValue: 380,
    cost: { gold: 375 },
    growth: 6,
    special: {
      nonLiving: true,
      vulnerablesToSpells: [Spells.Armageddon, Spells.Fireball, Spells.Inferno],
      immunity: [Spells.IceBolt, Spells.FrostRing],
    },
    description:
      'Ranged (24 shots), Elemental, Ice immunity, Vulnerable to Fireball, Inferno and Armageddon, +100% to basic damage to Fire and Energy Elementals, Casts Protection from Water',
  },
  {
    name: 'Fire Elemental',
    nativeTerrain: Terrains.Hightlands,
    townId: Towns.Conflux,
    id: 119,
    minDamage: 4,
    maxDamage: 6,
    health: 35,
    level: 4,
    attack: 10,
    defense: 8,
    hits: 1,
    ranged: false,
    speed: 6,
    aiValue: 345,
    cost: { gold: 350 },
    growth: 5,
    special: {
      nonLiving: true,
      vulnerablesToSpells: [Spells.IceBolt, Spells.FrostRing],
      immunityToSpellElement: ['fire'],
      immunity: [Spells.MagicArrow],
    },
    description: 'Elemental, Ice vulnerability, Fire immunity, +100% to basic damage to Water and Ice Elementals',
  },
  {
    name: 'Energy Elemental',
    nativeTerrain: Terrains.Hightlands,
    townId: Towns.Conflux,
    id: 120,
    minDamage: 4,
    maxDamage: 6,
    health: 35,
    level: 4,
    attack: 12,
    defense: 8,
    hits: 1,
    ranged: false,
    speed: 8,
    aiValue: 470,
    cost: { gold: 400 },
    growth: 5,
    special: {
      nonLiving: true,
      vulnerablesToSpells: [Spells.IceBolt, Spells.FrostRing],
      immunityToSpellElement: ['fire'],
      immunity: [Spells.MagicArrow],
    },
    description:
      'Elemental, Flying, Ice vulnerability, Fire immunity, +100% to basic damage to Water and Ice Elementals, Casts Protection from Fire',
  },
  {
    name: 'Earth Elemental',
    nativeTerrain: Terrains.Hightlands,
    townId: Towns.Conflux,
    id: 121,
    minDamage: 4,
    maxDamage: 8,
    health: 40,
    level: 5,
    attack: 10,
    defense: 10,
    hits: 1,
    ranged: false,
    speed: 4,
    aiValue: 330,
    cost: { gold: 400 },
    growth: 4,
    special: {
      nonLiving: true,
      vulnerablesToSpells: [Spells.MeteorShower],
      immunity: [Spells.LightningBolt, Spells.ChainLightning, Spells.Armageddon, Spells.TitansLightningBolt],
    },
    description:
      'Elemental, Meteor Shower vulnerability, Lightning and Armageddon immunity, +100% to basic damage to Air and Storm Elementals',
  },
  {
    name: 'Magma Elemental',
    nativeTerrain: Terrains.Hightlands,
    townId: Towns.Conflux,
    id: 122,
    minDamage: 6,
    maxDamage: 10,
    health: 40,
    level: 5,
    attack: 11,
    defense: 11,
    hits: 1,
    ranged: false,
    speed: 6,
    aiValue: 490,
    cost: { gold: 500 },
    growth: 4,
    special: {
      nonLiving: true,
      vulnerablesToSpells: [Spells.MeteorShower],
      immunity: [Spells.LightningBolt, Spells.ChainLightning, Spells.Armageddon, Spells.TitansLightningBolt],
    },
    description:
      'Elemental, Meteor Shower vulnerability, Lightning and Armageddon immunity, +100% to basic damage to Air and Storm Elementals, Casts Protection from Earth',
  },
  {
    name: 'Psychic Elemental',
    nativeTerrain: Terrains.Hightlands,
    townId: Towns.Conflux,
    id: 123,
    minDamage: 10,
    maxDamage: 20,
    health: 75,
    level: 6,
    attack: 15,
    defense: 13,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 1669,
    cost: { gold: 950 },
    growth: 2,
    special: {
      nonLiving: true,
    },
    description:
      'Elemental, Attacks all adjacent enemies without retaliation, -50% damage to creatures with Mind immunity',
  },
  {
    name: 'Magic Elemental',
    nativeTerrain: Terrains.Hightlands,
    townId: Towns.Conflux,
    id: 124,
    minDamage: 15,
    maxDamage: 25,
    health: 80,
    level: 6,
    attack: 15,
    defense: 13,
    hits: 1,
    ranged: false,
    speed: 9,
    aiValue: 2012,
    cost: { gold: 1200 },
    growth: 2,
    special: {
      nonLiving: true,
      immunityToSpellLevels: [1, 2, 3, 4, 5],
    },
    description:
      'Elemental, Attacks all adjacent enemies without retaliation, Magic immunity, -50% damage to creatures with Magic immunity',
  },
  {
    name: 'Firebird',
    nativeTerrain: Terrains.Hightlands,
    townId: Towns.Conflux,
    id: 125,
    minDamage: 30,
    maxDamage: 40,
    health: 150,
    level: 7,
    attack: 18,
    defense: 18,
    hits: 1,
    ranged: false,
    speed: 15,
    aiValue: 4336,
    cost: { gold: 2000 },
    growth: 1,
    special: {
      flying: true,
    },
    description: 'Flying, Breath attack, 50% fire resistance',
  },
  {
    name: 'Phoenix',
    nativeTerrain: Terrains.Hightlands,
    townId: Towns.Conflux,
    id: 126,
    minDamage: 30,
    maxDamage: 40,
    health: 200,
    level: 7,
    attack: 21,
    defense: 18,
    hits: 1,
    ranged: false,
    speed: 21,
    aiValue: 6721,
    cost: { gold: 3000, mercury: 1 },
    growth: 1,
    special: {
      flying: true,
      immunityToSpellElement: ['fire'],
      immunity: [Spells.MagicArrow],
    },
    description: 'Flying, Breath attack, Fire immunity, Rebirth',
  },
  {
    name: 'Peasant',
    nativeTerrain: 0,
    id: 127,
    townId: 0,
    minDamage: 1,
    maxDamage: 1,
    health: 1,
    level: 1,
    attack: 1,
    defense: 1,
    hits: 1,
    ranged: false,
    speed: 3,
    aiValue: 15,
    cost: { gold: 10 },
    growth: 25,
  },
  {
    name: 'Halfling',
    nativeTerrain: 0,
    id: 128,
    townId: 0,
    minDamage: 1,
    maxDamage: 3,
    health: 4,
    level: 1,
    attack: 4,
    defense: 2,
    hits: 1,
    ranged: true,
    speed: 5,
    aiValue: 75,
    cost: { gold: 40 },
    growth: 15,
    description: 'Ranged (24 shots), Positive Luck',
  },
  {
    name: 'Boar',
    nativeTerrain: 0,
    id: 129,
    townId: 0,
    minDamage: 2,
    maxDamage: 3,
    health: 15,
    level: 2,
    attack: 6,
    defense: 5,
    hits: 1,
    ranged: false,
    speed: 6,
    aiValue: 145,
    cost: { gold: 150 },
    growth: 8,
  },
  {
    name: 'Rogue',
    nativeTerrain: 0,
    id: 130,
    townId: 0,
    minDamage: 2,
    maxDamage: 4,
    health: 10,
    level: 2,
    attack: 8,
    defense: 3,
    hits: 1,
    ranged: false,
    speed: 6,
    aiValue: 135,
    cost: { gold: 100 },
    growth: 8,
    description: 'Spying',
  },
  {
    name: 'Nomad',
    nativeTerrain: 0,
    id: 131,
    townId: 0,
    minDamage: 2,
    maxDamage: 6,
    health: 30,
    level: 3,
    attack: 9,
    defense: 8,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 345,
    cost: { gold: 200 },
    growth: 7,
    description: 'Sandwalker',
  },
  {
    name: 'Mummy',
    nativeTerrain: 0,
    id: 132,
    townId: 0,
    minDamage: 3,
    maxDamage: 5,
    health: 30,
    level: 3,
    attack: 7,
    defense: 7,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 270,
    cost: { gold: 300 },
    growth: 7,
    special: {
      undead: true,
    },
    description: 'Undead, Curse',
  },
  {
    name: 'Sharpshooter',
    nativeTerrain: 0,
    id: 133,
    townId: 0,
    minDamage: 8,
    maxDamage: 10,
    health: 15,
    level: 4,
    attack: 12,
    defense: 10,
    hits: 1,
    ranged: true,
    speed: 9,
    aiValue: 585,
    cost: { gold: 400 },
    growth: 4,
    description: 'Ranged (32 shots), No range and obstacle penalty',
  },
  {
    name: 'Troll',
    nativeTerrain: 0,
    id: 134,
    townId: 0,
    minDamage: 10,
    maxDamage: 15,
    health: 40,
    level: 5,
    attack: 14,
    defense: 7,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 1024,
    cost: { gold: 500 },
    growth: 3,
    description: 'Regeneration',
  },
  {
    name: 'Gold Golem',
    nativeTerrain: 0,
    id: 135,
    townId: 0,
    minDamage: 8,
    maxDamage: 10,
    health: 50,
    level: 5,
    attack: 11,
    defense: 12,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 600,
    cost: { gold: 500 },
    growth: 3,
    special: {
      nonLiving: true,
      spellDamageResistance: 85,
    },
    description: 'Unliving, Spell Damage Resistance 85%',
  },
  {
    name: 'Diamond Golem',
    nativeTerrain: 0,
    id: 136,
    townId: 0,
    minDamage: 10,
    maxDamage: 14,
    health: 60,
    level: 6,
    attack: 13,
    defense: 12,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 775,
    cost: { gold: 750 },
    growth: 2,
    special: {
      nonLiving: true,
      spellDamageResistance: 95,
    },
    description: 'Unliving, Spell Damage Resistance 95%',
  },
  {
    name: 'Enchanter',
    nativeTerrain: 0,
    id: 137,
    townId: 0,
    minDamage: 14,
    maxDamage: 14,
    health: 30,
    level: 6,
    attack: 17,
    defense: 12,
    hits: 1,
    ranged: true,
    speed: 9,
    aiValue: 1210,
    cost: { gold: 750 },
    growth: 2,
    description: 'Ranged (32 shots), No melee and obstacle penalty, Spellcaster',
  },
  {
    name: 'Faerie Dragon',
    nativeTerrain: 0,
    id: 138,
    townId: 0,
    minDamage: 20,
    maxDamage: 30,
    health: 500,
    level: 7,
    attack: 20,
    defense: 20,
    hits: 1,
    ranged: false,
    speed: 15,
    aiValue: 30501,
    cost: { gold: 10000, gem: 8 },
    growth: 1,
    special: {
      flying: true,
    },
    description: 'Dragon, Flying, Spellcaster, Magic Mirror',
  },
  {
    name: 'Rust Dragon',
    nativeTerrain: 0,
    id: 139,
    townId: 0,
    minDamage: 50,
    maxDamage: 50,
    health: 750,
    level: 7,
    attack: 30,
    defense: 30,
    hits: 1,
    ranged: false,
    speed: 17,
    aiValue: 26433,
    cost: { gold: 15000, sulfur: 14 },
    growth: 1,
    special: {
      flying: true,
    },
    description: 'Dragon, Flying, Breath attack, Acid breath',
  },
  {
    name: 'Crystal Dragon',
    nativeTerrain: 0,
    id: 140,
    townId: 0,
    minDamage: 60,
    maxDamage: 75,
    health: 800,
    level: 7,
    attack: 40,
    defense: 40,
    hits: 1,
    ranged: false,
    speed: 16,
    aiValue: 39338,
    cost: { gold: 20000, crystal: 10 },
    growth: 1,
    special: {
      flying: true,
    },
    description: 'Dragon, Crystal generation, Magic resistance 20%',
  },
  {
    name: 'Azure Dragon',
    nativeTerrain: 0,
    id: 141,
    townId: 0,
    minDamage: 70,
    maxDamage: 80,
    health: 1000,
    level: 7,
    attack: 50,
    defense: 50,
    hits: 1,
    ranged: false,
    speed: 19,
    aiValue: 78845,
    cost: { gold: 30000, mercury: 20 },
    growth: 1,
    special: {
      flying: true,
      immunityToSpellLevels: [1, 2, 3],
    },
    description: 'Dragon, Flying, Breath attack, Fear, Resist lvl 1–3 spells, Resist Fear',
  },
  {
    name: 'Ballista',
    nativeTerrain: 0,
    id: 142,
    townId: 0,
    minDamage: 2,
    maxDamage: 3,
    health: 250,
    level: 5,
    attack: 10,
    defense: 10,
    hits: 1,
    ranged: true,
    hexs: 2,
    speed: 0,
    cost: { gold: 2500 },
    shots: 24,
    description: 'Ranged (24 Shots)',
  },
  {
    name: 'Nymph',
    nativeTerrain: Terrains.Swamp,
    id: 143,
    townId: Towns.Cove,
    minDamage: 1,
    maxDamage: 2,
    health: 4,
    level: 1,
    attack: 5,
    defense: 2,
    hits: 1,
    ranged: false,
    speed: 6,
    aiValue: 57,
    cost: { gold: 35 },
    growth: 16,
    special: {
      flying: true,
      immunity: [Spells.IceBolt, Spells.FrostRing],
    },
    description: 'Teleporting, Immune to ice',
  },
  {
    name: 'Oceanid',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Cove,
    id: 144,
    minDamage: 1,
    maxDamage: 3,
    health: 4,
    level: 1,
    attack: 6,
    defense: 2,
    hits: 1,
    ranged: false,
    speed: 8,
    aiValue: 75,
    cost: { gold: 45 },
    growth: 16,
    special: {
      flying: true,
      immunity: [Spells.IceBolt, Spells.FrostRing],
    },
    description: 'Teleporting, Immune to ice',
  },
  {
    name: 'Crew Mate',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Cove,
    id: 145,
    minDamage: 2,
    maxDamage: 4,
    health: 15,
    level: 2,
    attack: 7,
    defense: 4,
    hits: 1,
    ranged: false,
    speed: 5,
    aiValue: 155,
    cost: { gold: 110 },
    growth: 9,
  },
  {
    name: 'Seaman',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Cove,
    id: 146,
    minDamage: 3,
    maxDamage: 4,
    health: 15,
    level: 2,
    attack: 8,
    defense: 6,
    hits: 1,
    ranged: false,
    speed: 6,
    aiValue: 174,
    cost: { gold: 140 },
    growth: 9,
  },
  {
    name: 'Pirate',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Cove,
    id: 147,
    minDamage: 3,
    maxDamage: 7,
    health: 15,
    level: 3,
    attack: 8,
    defense: 6,
    hits: 1,
    ranged: true,
    speed: 6,
    aiValue: 312,
    cost: { gold: 225 },
    growth: 7,
    special: {
      noMeleePenalty: true,
      ranged: true,
      shots: 4,
    },
    description: 'Ranged (4 shots), No melee penalty',
  },
  {
    name: 'Corsair',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Cove,
    id: 148,
    minDamage: 3,
    maxDamage: 7,
    health: 15,
    level: 3,
    attack: 10,
    defense: 8,
    hits: 1,
    ranged: true,
    speed: 7,
    aiValue: 407,
    cost: { gold: 275 },
    growth: 7,
    special: {
      noMeleePenalty: true,
      noEnemyRetaliation: true,
      ranged: true,
      shots: 4,
    },
    description: 'Ranged (4 shots), No melee penalty, No enemy retaliation',
  },
  {
    name: 'Sea Dog',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Cove,
    id: 149,
    minDamage: 3,
    maxDamage: 7,
    health: 15,
    level: 3,
    attack: 12,
    defense: 11,
    hits: 1,
    ranged: true,
    speed: 8,
    aiValue: 602,
    cost: { gold: 375 },
    growth: 7,
    special: {
      noMeleePenalty: true,
      noEnemyRetaliation: true,
      ranged: true,
      shots: 12,
    },
    description: 'Ranged (12 shots), No melee penalty, No enemy retaliation, Accurate Shot',
  },
  {
    name: 'Stormbird',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Cove,
    id: 150,
    minDamage: 6,
    maxDamage: 9,
    health: 30,
    level: 4,
    attack: 10,
    defense: 8,
    hits: 1,
    ranged: false,
    speed: 9,
    aiValue: 502,
    cost: { gold: 275 },
    growth: 4,
    special: {
      flying: true,
    },
    description: 'Flying',
  },
  {
    name: 'Ayssid',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Cove,
    id: 151,
    minDamage: 6,
    maxDamage: 10,
    health: 30,
    level: 4,
    attack: 11,
    defense: 8,
    hits: 1,
    ranged: false,
    speed: 11,
    aiValue: 645,
    cost: { gold: 325 },
    growth: 4,
    special: {
      flying: true,
    },
    description: 'Flying, Ferocity',
  },
  {
    name: 'Sea Witch',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Cove,
    id: 152,
    minDamage: 10,
    maxDamage: 14,
    health: 35,
    level: 5,
    attack: 12,
    defense: 7,
    hits: 1,
    ranged: true,
    speed: 6,
    aiValue: 790,
    cost: { gold: 515 },
    growth: 3,
    special: {
      ranged: true,
      shots: 12,
    },
    description: 'Ranged (12 shots), Casts Weakness / Disrupting Ray',
  },
  {
    name: 'Sorceress',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Cove,
    id: 153,
    minDamage: 10,
    maxDamage: 16,
    health: 35,
    level: 5,
    attack: 12,
    defense: 9,
    hits: 1,
    ranged: true,
    speed: 7,
    aiValue: 852,
    cost: { gold: 565 },
    growth: 3,
    special: {
      ranged: true,
      shots: 12,
    },
    description: 'Ranged (12 shots), Casts Weakness / Disrupting Ray',
  },
  {
    name: 'Nix',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Cove,
    id: 154,
    minDamage: 18,
    maxDamage: 22,
    health: 80,
    level: 6,
    attack: 13,
    defense: 16,
    hits: 1,
    ranged: false,
    speed: 6,
    aiValue: 1415,
    cost: { gold: 1000 },
    growth: 2,
    special: {
      ignoreEnemyAttackPercents: 30,
    },
    description: 'Ignores 30% of enemy attack value',
  },
  {
    name: 'Nix Warrior',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Cove,
    id: 155,
    minDamage: 18,
    maxDamage: 22,
    health: 90,
    level: 6,
    attack: 14,
    defense: 17,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 2116,
    cost: { gold: 1300 },
    growth: 2,
    special: {
      ignoreEnemyAttackPercents: 60,
    },
    description: 'Ignores 60% of enemy attack value',
  },
  {
    name: 'Sea Serpent',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Cove,
    id: 156,
    minDamage: 30,
    maxDamage: 55,
    health: 180,
    level: 7,
    attack: 22,
    defense: 16,
    hits: 1,
    ranged: false,
    speed: 9,
    aiValue: 3953,
    cost: { gold: 2200, sulfur: 1 },
    growth: 1,
    special: {
      poisonChance: 30,
    },
    description: 'Poisonous',
  },
  {
    name: 'Haspid',
    nativeTerrain: Terrains.Swamp,
    townId: Towns.Cove,
    id: 157,
    minDamage: 30,
    maxDamage: 55,
    health: 300,
    level: 7,
    attack: 29,
    defense: 20,
    hits: 1,
    ranged: false,
    speed: 12,
    aiValue: 7220,
    cost: { gold: 4000, sulfur: 2 },
    growth: 1,
    special: {
      poisonChance: 30,
    },
    description: 'Poisonous, Revenge',
  },
  {
    name: 'Fangarm',
    nativeTerrain: 0,
    id: 158,
    minDamage: 8,
    maxDamage: 12,
    health: 50,
    level: 5,
    attack: 12,
    defense: 12,
    hits: 1,
    ranged: false,
    speed: 6,
    aiValue: 929,
    cost: { gold: 600 },
    growth: 3,
    special: {
      flying: true,
    },
    description: 'Flying, Mind spell immunity, Unlimited retaliations, Casts Hypnotize on attacked stack',
  },
  {
    name: 'Satyr',
    nativeTerrain: 0,
    townId: 0,
    id: 159,
    minDamage: 6,
    maxDamage: 10,
    health: 35,
    level: 4,
    attack: 10,
    defense: 11,
    hits: 1,
    ranged: false,
    speed: 7,
    aiValue: 518,
    cost: { gold: 300 },
    growth: 4,
    description: 'Casts Mirth',
  },
  {
    name: 'Leprechaun',
    aiValue: 190,
    attack: 8,
    townId: 0,
    cost: { gold: 100 },
    defense: 5,
    fightValue: 190,
    growth: 9,
    health: 15,
    hits: 1,
    id: 160,
    level: 2,
    maxDamage: 5,
    minDamage: 3,
    nativeTerrain: 0,
    speed: 5,
    ranged: false,
    description: 'Doubles friendly unit Luck chance, Casts Fortune',
  },
  {
    name: 'Cannon',
    nativeTerrain: 0,
    id: 161,
    townId: 0,
    minDamage: 4,
    maxDamage: 7,
    health: 250,
    level: 6,
    attack: 20,
    defense: 10,
    hits: 1,
    ranged: true,
    hexs: 2,
    speed: 0,
    cost: { gold: 4000 },
    shots: 8,
    description: 'Ranged (8 shots)',
  },
  {
    name: 'Steel Golem',
    nativeTerrain: 0,
    id: 162,
    townId: 0,
    minDamage: 6,
    maxDamage: 8,
    health: 45,
    level: 4,
    cost: { gold: 400 },
    growth: 4,
    aiValue: 597,
    fightValue: 597,
    attack: 10,
    defense: 11,
    speed: 6,
    hits: 1,
    ranged: false,
    special: {
      nonLiving: true,
      spellDamageResistance: 80,
    },
    description: 'Unliving, Spell Damage Resistance 80%',
  },
  {
    name: 'Halfling',
    nativeTerrain: Terrains.Wasteland,
    id: 163,
    townId: Towns.Factory,
    attack: 4,
    defense: 2,
    minDamage: 1,
    maxDamage: 3,
    health: 4,
    speed: 5,
    growth: 15,
    hits: 1,
    level: 1,
    ranged: true,
    shots: 24,
    cost: {
      gold: 40,
    },
    description: 'Ranged (24 shots), always has +1 luck',
  },
  {
    name: 'Halfling Grenadier',
    nativeTerrain: Terrains.Wasteland,
    id: 164,
    townId: Towns.Factory,
    attack: 5,
    defense: 2,
    minDamage: 2,
    maxDamage: 3,
    health: 4,
    speed: 6,
    growth: 15,
    hits: 1,
    level: 1,
    ranged: true,
    shots: 24,
    cost: {
      gold: 65,
    },
    description: "Ranged (24 shots), Always has +1 luck, Ranged attack ignores 20% of enemy's defense skill",
  },
  {
    name: 'Mechanic',
    nativeTerrain: Terrains.Wasteland,
    id: 165,
    townId: Towns.Factory,
    attack: 6,
    defense: 5,
    minDamage: 2,
    maxDamage: 4,
    health: 14,
    speed: 6,
    growth: 8,
    hits: 1,
    level: 2,
    ranged: false,
    cost: {
      gold: 140,
    },
    description: 'Breath attack, Repairs mechanical creatures',
  },
  {
    name: 'Engineer',
    nativeTerrain: Terrains.Wasteland,
    id: 166,
    townId: Towns.Factory,
    attack: 7,
    defense: 5,
    minDamage: 2,
    maxDamage: 5,
    health: 16,
    speed: 7,
    growth: 8,
    hits: 1,
    level: 2,
    ranged: false,
    cost: {
      gold: 170,
    },
    description: 'Breath attack, Repairs mechanical creatures',
  },
  {
    name: 'Armadillo',
    nativeTerrain: Terrains.Wasteland,
    id: 167,
    townId: Towns.Factory,
    attack: 5,
    defense: 10,
    minDamage: 3,
    maxDamage: 5,
    health: 25,
    speed: 4,
    growth: 6,
    hits: 1,
    level: 3,
    hexs: 2,
    ranged: false,
    cost: {
      gold: 200,
    },
  },
  {
    name: 'Bellwether Armadillo',
    nativeTerrain: Terrains.Wasteland,
    id: 168,
    townId: Towns.Factory,
    attack: 6,
    defense: 11,
    minDamage: 3,
    maxDamage: 5,
    health: 25,
    speed: 6,
    growth: 6,
    hexs: 2,
    hits: 1,
    level: 3,
    ranged: false,
    cost: {
      gold: 230,
    },
  },
  {
    name: 'Automaton',
    nativeTerrain: Terrains.Wasteland,
    id: 169,
    townId: Towns.Factory,
    attack: 12,
    defense: 10,
    minDamage: 7,
    maxDamage: 7,
    health: 30,
    speed: 8,
    growth: 5,
    hits: 1,
    level: 4,
    ranged: false,
    cost: {
      gold: 350,
    },
    description: 'Mechanical, Detonation at death',
  },
  {
    name: 'Sentinel Automaton',
    nativeTerrain: Terrains.Wasteland,
    id: 170,
    townId: Towns.Factory,
    attack: 12,
    defense: 10,
    minDamage: 9,
    maxDamage: 9,
    health: 30,
    speed: 9,
    growth: 5,
    hits: 1,
    level: 4,
    ranged: false,
    cost: {
      gold: 450,
    },
    special: {
      noEnemyRetaliation: true,
    },
    description: 'Mechanical, Detonation at death, No enemy retaliation',
  },
  {
    name: 'Sandworm',
    nativeTerrain: Terrains.Wasteland,
    id: 171,
    townId: Towns.Factory,
    attack: 13,
    defense: 12,
    minDamage: 12,
    maxDamage: 16,
    health: 50,
    speed: 8,
    growth: 3,
    hexs: 2,
    hits: 1,
    level: 5,
    ranged: false,
    cost: {
      gold: 575,
    },
    special: {
      immunity: [Spells.Blind],
    },
    description: 'Immune to blinding, Immune to petrification',
  },
  {
    name: 'Olgoi-Khorkhoi',
    nativeTerrain: Terrains.Wasteland,
    id: 172,
    townId: Towns.Factory,
    attack: 15,
    defense: 12,
    minDamage: 12,
    maxDamage: 16,
    health: 60,
    speed: 10,
    growth: 3,
    hexs: 2,
    hits: 1,
    level: 5,
    ranged: false,
    cost: {
      gold: 650,
    },
    special: {
      immunity: [Spells.Blind],
    },
    description: 'Immune to blinding, Immune to petrification, Devours corpses for additional strikes',
  },
  {
    name: 'Gunslinger',
    nativeTerrain: Terrains.Wasteland,
    id: 173,
    townId: Towns.Factory,
    attack: 17,
    defense: 12,
    minDamage: 14,
    maxDamage: 24,
    health: 45,
    speed: 7,
    growth: 2,
    shots: 16,
    hits: 1,
    level: 6,
    ranged: true,
    cost: {
      gold: 800,
    },
    description: 'Ranged attack (16 shots), Preemptive shot once per round',
  },
  {
    name: 'Bounty Hunter',
    nativeTerrain: Terrains.Wasteland,
    id: 174,
    townId: Towns.Factory,
    attack: 18,
    defense: 14,
    minDamage: 14,
    maxDamage: 24,
    health: 45,
    speed: 8,
    growth: 2,
    shots: 24,
    hits: 1,
    level: 6,
    ranged: true,
    cost: {
      gold: 1100,
    },
    description: 'Ranged attack (24 shots), Preemptive shot once per round',
  },
  {
    name: 'Couatl',
    nativeTerrain: Terrains.Wasteland,
    id: 175,
    townId: Towns.Factory,
    attack: 17,
    defense: 17,
    minDamage: 25,
    maxDamage: 45,
    health: 160,
    speed: 11,
    hexs: 2,
    growth: 1,
    hits: 1,
    level: 7,
    ranged: false,
    cost: {
      gold: 2000,
    },
    special: {
      flying: true,
    },
    description: 'Meditation but skips a turn',
  },
  {
    name: 'Crimson Couatl',
    nativeTerrain: Terrains.Wasteland,
    id: 176,
    townId: Towns.Factory,
    attack: 21,
    defense: 21,
    minDamage: 25,
    maxDamage: 45,
    health: 200,
    speed: 15,
    hexs: 2,
    growth: 1,
    hits: 1,
    level: 7,
    ranged: false,
    cost: {
      gold: 3500,
      crystal: 1,
    },
    special: {
      flying: true,
    },
    description: 'Meditation without skipping a turn',
  },
  {
    name: 'Dreadnought',
    nativeTerrain: Terrains.Wasteland,
    id: 177,
    townId: Towns.Factory,
    attack: 18,
    defense: 20,
    minDamage: 40,
    maxDamage: 50,
    health: 200,
    speed: 6,
    hexs: 2,
    growth: 1,
    hits: 1,
    level: 7,
    ranged: false,
    cost: {
      gold: 2500,
      crystal: 1,
    },
    description: 'Mechanical, Heat stroke',
  },
  {
    name: 'Juggernaut',
    nativeTerrain: Terrains.Wasteland,
    id: 178,
    townId: Towns.Factory,
    attack: 23,
    defense: 23,
    minDamage: 40,
    maxDamage: 50,
    health: 300,
    speed: 7,
    hexs: 2,
    growth: 1,
    hits: 1,
    level: 7,
    ranged: false,
    cost: {
      gold: 4000,
      crystal: 2,
    },
    description: 'Mechanical, Heat stroke',
  },
]
