import { Hero } from '@/models/Hero'
import { Classes, Creatures, SecondarySkills, Spells } from '@/models/enums'

export const heroes: Array<Hero> = [
  {
    id: 1,
    name: 'Orrin',
    classId: Classes.Knight,
    specialtySkill: SecondarySkills.Archery,
  },
  {
    id: 2,
    name: 'Valeska',
    classId: Classes.Knight,
    specialtyUnit: [Creatures.Archer, Creatures.Marksman],
  },
  {
    id: 3,
    name: 'Edric',
    classId: Classes.Knight,
    specialtyUnit: [Creatures.Griffin, Creatures.RoyalGriffin],
  },
  {
    id: 4,
    name: 'Sylvia',
    classId: Classes.Knight,
  },
  {
    id: 5,
    name: 'Lord Haart',
    classId: Classes.Knight,
  },
  {
    id: 6,
    name: 'Sorsha',
    classId: Classes.Knight,
    specialtyUnit: [Creatures.Swordsman, Creatures.Crusader],
  },
  {
    id: 7,
    name: 'Christian',
    classId: Classes.Knight,
    specialtyUnit: [Creatures.Ballista],
  },
  {
    id: 8,
    name: 'Tyris',
    classId: Classes.Knight,
    specialtyUnit: [Creatures.Cavalier, Creatures.Champion],
  },
  {
    id: 9,
    name: 'Rion',
    classId: Classes.Cleric,
  },
  {
    id: 10,
    name: 'Adela',
    classId: Classes.Cleric,
    specialtySpell: Spells.Bless,
  },
  {
    id: 11,
    name: 'Cuthbert',
    classId: Classes.Cleric,
    specialtySpell: Spells.Weakness,
  },
  {
    id: 12,
    name: 'Adelaide',
    classId: Classes.Cleric,
    specialtySpell: Spells.FrostRing,
  },
  {
    id: 13,
    name: 'Ingham',
    classId: Classes.Cleric,
    specialtyUnit: [Creatures.Monk, Creatures.Zealot],
  },
  {
    id: 14,
    name: 'Sanya',
    classId: Classes.Cleric,
  },
  {
    id: 15,
    name: 'Loynis',
    classId: Classes.Cleric,
    specialtySpell: Spells.Prayer,
  },
  {
    id: 16,
    name: 'Caitlin',
    classId: Classes.Cleric,
  },
  {
    id: 17,
    name: 'Mephala',
    classId: Classes.Ranger,
    specialtySkill: SecondarySkills.Armorer,
  },
  {
    id: 18,
    name: 'Ufretin',
    classId: Classes.Ranger,
    specialtyUnit: [Creatures.Dwarf, Creatures.BattleDwarf],
  },
  {
    id: 19,
    name: 'Jenova',
    classId: Classes.Ranger,
  },
  {
    id: 20,
    name: 'Ryland',
    classId: Classes.Ranger,
    specialtyUnit: [Creatures.DendroidGuard, Creatures.DendroidSoldier],
  },
  {
    id: 21,
    name: 'Thorgrim',
    classId: Classes.Ranger,
  },
  {
    id: 22,
    name: 'Ivor',
    classId: Classes.Ranger,
    specialtyUnit: [Creatures.WoodElf, Creatures.GrandElf],
  },
  {
    id: 23,
    name: 'Clancy',
    classId: Classes.Ranger,
    specialtyUnit: [Creatures.Unicorn, Creatures.WarUnicorn],
  },
  {
    id: 24,
    name: 'Kyrre',
    classId: Classes.Ranger,
  },
  {
    id: 25,
    name: 'Coronius',
    classId: Classes.Druid,
    specialtySpell: Spells.Slayer,
  },
  {
    id: 26,
    name: 'Uland',
    classId: Classes.Druid,
  },
  {
    id: 27,
    name: 'Elleshar',
    classId: Classes.Druid,
  },
  {
    id: 28,
    name: 'Gem',
    classId: Classes.Druid,
  },
  {
    id: 29,
    name: 'Malcom',
    classId: Classes.Druid,
  },
  {
    id: 30,
    name: 'Melodia',
    classId: Classes.Druid,
  },
  {
    id: 31,
    name: 'Alagar',
    classId: Classes.Druid,
    specialtySpell: Spells.IceBolt,
  },
  {
    id: 32,
    name: 'Aeris',
    classId: Classes.Druid,
    specialtyUnit: [Creatures.Pegasus, Creatures.SilverPegasus],
  },
  {
    id: 33,
    name: 'Piquedram',
    classId: Classes.Alchemist,
    specialtyUnit: [Creatures.StoneGargoyle, Creatures.ObsidianGargoyle],
  },
  {
    id: 34,
    name: 'Thane',
    classId: Classes.Alchemist,
    specialtyUnit: [Creatures.Genie, Creatures.MasterGenie],
  },
  {
    id: 35,
    name: 'Josephine',
    classId: Classes.Alchemist,
    specialtyUnit: [Creatures.StoneGolem, Creatures.IronGolem],
  },
  {
    id: 36,
    name: 'Neela',
    classId: Classes.Alchemist,
    specialtySkill: SecondarySkills.Armorer,
  },
  {
    id: 37,
    name: 'Torosar',
    classId: Classes.Alchemist,
    specialtyUnit: [Creatures.Ballista],
  },
  {
    id: 38,
    name: 'Fafner',
    classId: Classes.Alchemist,
    specialtyUnit: [Creatures.Naga, Creatures.NagaQueen],
  },
  {
    id: 39,
    name: 'Rissa',
    classId: Classes.Alchemist,
  },
  {
    id: 40,
    name: 'Iona',
    classId: Classes.Alchemist,
    specialtyUnit: [Creatures.Genie, Creatures.MasterGenie],
  },
  {
    id: 41,
    name: 'Astral',
    classId: Classes.Wizard,
  },
  {
    id: 42,
    name: 'Halon',
    classId: Classes.Wizard,
  },
  {
    id: 43,
    name: 'Serena',
    classId: Classes.Wizard,
  },
  {
    id: 44,
    name: 'Daremyth',
    classId: Classes.Wizard,
  },
  {
    id: 45,
    name: 'Theodorus',
    classId: Classes.Wizard,
    specialtyUnit: [Creatures.Mage, Creatures.ArchMage],
  },
  {
    id: 46,
    name: 'Solmyr',
    classId: Classes.Wizard,
    specialtySpell: Spells.ChainLightning,
  },
  {
    id: 47,
    name: 'Cyra',
    classId: Classes.Wizard,
  },
  {
    id: 48,
    name: 'Aine',
    classId: Classes.Wizard,
  },
  {
    id: 49,
    name: 'Fiona',
    classId: Classes.Demoniac,
    specialtyUnit: [Creatures.HellHound, Creatures.Cerberus],
  },
  {
    id: 50,
    name: 'Rashka',
    classId: Classes.Demoniac,
    specialtyUnit: [Creatures.Efreet, Creatures.EfreetSultan],
  },
  {
    id: 51,
    name: 'Marius',
    classId: Classes.Demoniac,
    specialtyUnit: [Creatures.Demon, Creatures.HornedDemon],
  },
  {
    id: 52,
    name: 'Ignatius',
    classId: Classes.Demoniac,
    specialtyUnit: [Creatures.Imp, Creatures.Familiar],
  },
  {
    id: 53,
    name: 'Octavia',
    classId: Classes.Demoniac,
  },
  {
    id: 54,
    name: 'Calh',
    classId: Classes.Demoniac,
    specialtyUnit: [Creatures.Gog, Creatures.Magog],
  },
  {
    id: 55,
    name: 'Pyre',
    classId: Classes.Demoniac,
    specialtyUnit: [Creatures.Ballista],
  },
  {
    id: 56,
    name: 'Nymus',
    classId: Classes.Demoniac,
    specialtyUnit: [Creatures.PitFiend, Creatures.PitLord],
  },
  {
    id: 57,
    name: 'Ayden',
    classId: Classes.Heretic,
  },
  {
    id: 58,
    name: 'Xyron',
    classId: Classes.Heretic,
    specialtySpell: Spells.Inferno,
  },
  {
    id: 59,
    name: 'Axsis',
    classId: Classes.Heretic,
  },
  {
    id: 60,
    name: 'Olema',
    classId: Classes.Heretic,
    specialtySpell: Spells.Weakness,
  },
  {
    id: 61,
    name: 'Calid',
    classId: Classes.Heretic,
  },
  {
    id: 62,
    name: 'Ash',
    classId: Classes.Heretic,
    specialtySpell: Spells.Bloodlust,
  },
  {
    id: 63,
    name: 'Zydar',
    classId: Classes.Heretic,
    specialtySkill: SecondarySkills.Sorcery,
  },
  {
    id: 64,
    name: 'Xarfax',
    classId: Classes.Heretic,
    specialtySpell: Spells.Fireball,
  },
  {
    id: 65,
    name: 'Straker',
    classId: Classes.DeathKnight,
    specialtyUnit: [Creatures.WalkingDead, Creatures.Zombie],
  },
  {
    id: 66,
    name: 'Vokial',
    classId: Classes.DeathKnight,
    specialtyUnit: [Creatures.Vampire, Creatures.VampireLord],
  },
  {
    id: 67,
    name: 'Moandor',
    classId: Classes.DeathKnight,
    specialtyUnit: [Creatures.Lich, Creatures.PowerLich],
  },
  {
    id: 68,
    name: 'Charna',
    classId: Classes.DeathKnight,
    specialtyUnit: [Creatures.Wight, Creatures.Wraith],
  },
  {
    id: 69,
    name: 'Tamika',
    classId: Classes.DeathKnight,
    specialtyUnit: [Creatures.BlackKnight, Creatures.DreadKnight],
  },
  {
    id: 70,
    name: 'Isra',
    classId: Classes.DeathKnight,
  },
  {
    id: 71,
    name: 'Clavius',
    classId: Classes.DeathKnight,
  },
  {
    id: 72,
    name: 'Galthran',
    classId: Classes.DeathKnight,
    specialtyUnit: [Creatures.Skeleton, Creatures.SkeletonWarrior],
  },
  {
    id: 73,
    name: 'Septienna',
    classId: Classes.Necromancer,
    specialtySpell: Spells.DestroyUndead,
  },
  {
    id: 74,
    name: 'Aislinn',
    classId: Classes.Necromancer,
    specialtySpell: Spells.MeteorShower,
  },
  {
    id: 75,
    name: 'Sandro',
    classId: Classes.Necromancer,
    specialtySkill: SecondarySkills.Sorcery,
  },
  {
    id: 76,
    name: 'Nimbus',
    classId: Classes.Necromancer,
  },
  {
    id: 77,
    name: 'Thant',
    classId: Classes.Necromancer,
  },
  {
    id: 78,
    name: 'Xsi',
    classId: Classes.Necromancer,
    specialtySpell: Spells.StoneSkin,
  },
  {
    id: 79,
    name: 'Vidomina',
    classId: Classes.Necromancer,
  },
  {
    id: 80,
    name: 'Nagash',
    classId: Classes.Necromancer,
  },
  {
    id: 81,
    name: 'Lorelei',
    classId: Classes.Overlord,
    specialtyUnit: [Creatures.Harpy, Creatures.HarpyHag],
  },
  {
    id: 82,
    name: 'Arlach',
    classId: Classes.Overlord,
    specialtyUnit: [Creatures.Ballista],
  },
  {
    id: 83,
    name: 'Dace',
    classId: Classes.Overlord,
    specialtyUnit: [Creatures.Minotaur, Creatures.MinotaurKing],
  },
  {
    id: 84,
    name: 'Ajit',
    classId: Classes.Overlord,
    specialtyUnit: [Creatures.Beholder, Creatures.EvilEye],
  },
  {
    id: 85,
    name: 'Damacon',
    classId: Classes.Overlord,
  },
  {
    id: 86,
    name: 'Gunnar',
    classId: Classes.Overlord,
  },
  {
    id: 87,
    name: 'Synca',
    classId: Classes.Overlord,
    specialtyUnit: [Creatures.Manticore, Creatures.Scorpicore],
  },
  {
    id: 88,
    name: 'Shakti',
    classId: Classes.Overlord,
    specialtyUnit: [Creatures.Troglodyte, Creatures.InfernalTroglodyte],
  },
  {
    id: 89,
    name: 'Alamar',
    classId: Classes.Warlock,
  },
  {
    id: 90,
    name: 'Jaegar',
    classId: Classes.Warlock,
  },
  {
    id: 91,
    name: 'Malekith',
    classId: Classes.Warlock,
    specialtySkill: SecondarySkills.Sorcery,
  },
  {
    id: 92,
    name: 'Jeddite',
    classId: Classes.Warlock,
  },
  {
    id: 93,
    name: 'Geon',
    classId: Classes.Warlock,
  },
  {
    id: 94,
    name: 'Deemer',
    classId: Classes.Warlock,
    specialtySpell: Spells.MeteorShower,
  },
  {
    id: 95,
    name: 'Sephinroth',
    classId: Classes.Warlock,
  },
  {
    id: 96,
    name: 'Darkstorn',
    classId: Classes.Warlock,
    specialtySpell: Spells.StoneSkin,
  },
  {
    id: 97,
    name: 'Yog',
    classId: Classes.Barbarian,
    specialtyUnit: [Creatures.Cyclops, Creatures.CyclopsKing],
  },
  {
    id: 98,
    name: 'Gurnisson',
    classId: Classes.Barbarian,
    specialtyUnit: [Creatures.Ballista],
  },
  {
    id: 99,
    name: 'Jabarkas',
    classId: Classes.Barbarian,
    specialtyUnit: [Creatures.Orc, Creatures.OrcChieftain],
  },
  {
    id: 100,
    name: 'Shiva',
    classId: Classes.Barbarian,
    specialtyUnit: [Creatures.Roc, Creatures.Thunderbird],
  },
  {
    id: 101,
    name: 'Gretchin',
    classId: Classes.Barbarian,
    specialtyUnit: [Creatures.Goblin, Creatures.Hobgoblin],
  },
  {
    id: 102,
    name: 'Krellion',
    classId: Classes.Barbarian,
    specialtyUnit: [Creatures.Ogre, Creatures.OgreMage],
  },
  {
    id: 103,
    name: 'Crag Hack',
    classId: Classes.Barbarian,
    specialtySkill: SecondarySkills.Offense,
  },
  {
    id: 104,
    name: 'Tyraxor',
    classId: Classes.Barbarian,
    specialtyUnit: [Creatures.WolfRider, Creatures.WolfRaider],
  },
  {
    id: 105,
    name: 'Gird',
    classId: Classes.BattleMage,
    specialtySkill: SecondarySkills.Sorcery,
  },
  {
    id: 106,
    name: 'Vey',
    classId: Classes.BattleMage,
    specialtyUnit: [Creatures.Ogre, Creatures.OgreMage],
  },
  {
    id: 107,
    name: 'Dessa',
    classId: Classes.BattleMage,
  },
  {
    id: 108,
    name: 'Terek',
    classId: Classes.BattleMage,
  },
  {
    id: 109,
    name: 'Zubin',
    classId: Classes.BattleMage,
    specialtySpell: Spells.Precision,
  },
  {
    id: 110,
    name: 'Gundula',
    classId: Classes.BattleMage,
    specialtySkill: SecondarySkills.Offense,
  },
  {
    id: 111,
    name: 'Oris',
    classId: Classes.BattleMage,
  },
  {
    id: 112,
    name: 'Saurug',
    classId: Classes.BattleMage,
  },
  {
    id: 113,
    name: 'Bron',
    classId: Classes.Beastmaster,
    specialtyUnit: [Creatures.Basilisk, Creatures.GreaterBasilisk],
  },
  {
    id: 114,
    name: 'Drakon',
    classId: Classes.Beastmaster,
    specialtyUnit: [Creatures.Gnoll, Creatures.GnollMarauder],
  },
  {
    id: 115,
    name: 'Wystan',
    classId: Classes.Beastmaster,
    specialtyUnit: [Creatures.Lizardman, Creatures.LizardWarrior],
  },
  {
    id: 116,
    name: 'Tazar',
    classId: Classes.Beastmaster,
    specialtySkill: SecondarySkills.Armorer,
  },
  {
    id: 117,
    name: 'Alkin',
    classId: Classes.Beastmaster,
    specialtyUnit: [Creatures.Gorgon, Creatures.MightyGorgon],
  },
  {
    id: 118,
    name: 'Korbac',
    classId: Classes.Beastmaster,
    specialtyUnit: [Creatures.SerpentFly, Creatures.DragonFly],
  },
  {
    id: 119,
    name: 'Gerwulf',
    classId: Classes.Beastmaster,
    specialtyUnit: [Creatures.Ballista],
  },
  {
    id: 120,
    name: 'Broghild',
    classId: Classes.Beastmaster,
    specialtyUnit: [Creatures.Wyvern, Creatures.WyvernMonarch],
  },
  {
    id: 121,
    name: 'Mirlanda',
    classId: Classes.Witch,
    specialtySpell: Spells.Weakness,
  },
  {
    id: 122,
    name: 'Rosic',
    classId: Classes.Witch,
  },
  {
    id: 123,
    name: 'Voy',
    classId: Classes.Witch,
  },
  {
    id: 124,
    name: 'Verdish',
    classId: Classes.Witch,
  },
  {
    id: 125,
    name: 'Merist',
    classId: Classes.Witch,
    specialtySpell: Spells.StoneSkin,
  },
  {
    id: 126,
    name: 'Styg',
    classId: Classes.Witch,
    specialtySkill: SecondarySkills.Sorcery,
  },
  {
    id: 127,
    name: 'Andra',
    classId: Classes.Witch,
  },
  {
    id: 128,
    name: 'Tiva',
    classId: Classes.Witch,
  },
  {
    id: 129,
    name: 'Pasis',
    classId: Classes.Planeswalker,
    specialtyUnit: [Creatures.PsychicElemental, Creatures.MagicElemental],
  },
  {
    id: 130,
    name: 'Thunar',
    classId: Classes.Planeswalker,
    specialtyUnit: [Creatures.EarthElemental, Creatures.MagmaElemental],
  },
  {
    id: 131,
    name: 'Ignissa',
    classId: Classes.Planeswalker,
    specialtyUnit: [Creatures.FireElemental, Creatures.EnergyElemental],
  },
  {
    id: 132,
    name: 'Lacus',
    classId: Classes.Planeswalker,
    specialtyUnit: [Creatures.WaterElemental, Creatures.IceElemental],
  },
  {
    id: 133,
    name: 'Monere',
    classId: Classes.Planeswalker,
    specialtyUnit: [Creatures.PsychicElemental, Creatures.MagicElemental],
  },
  {
    id: 134,
    name: 'Erdamon',
    classId: Classes.Planeswalker,
    specialtyUnit: [Creatures.EarthElemental, Creatures.MagmaElemental],
  },
  {
    id: 135,
    name: 'Fiur',
    classId: Classes.Planeswalker,
    specialtyUnit: [Creatures.FireElemental, Creatures.EnergyElemental],
  },
  {
    id: 136,
    name: 'Kalt',
    classId: Classes.Planeswalker,
    specialtyUnit: [Creatures.WaterElemental, Creatures.IceElemental],
  },
  {
    id: 137,
    name: 'Luna',
    classId: Classes.Elementalist,
    specialtySpell: Spells.Firewall,
  },
  {
    id: 138,
    name: 'Brissa',
    classId: Classes.Elementalist,
  },
  {
    id: 139,
    name: 'Ciele',
    classId: Classes.Elementalist,
    specialtySpell: Spells.MagicArrow,
  },
  {
    id: 140,
    name: 'Labetha',
    classId: Classes.Elementalist,
    specialtySpell: Spells.StoneSkin,
  },
  {
    id: 141,
    name: 'Inteus',
    classId: Classes.Elementalist,
    specialtySpell: Spells.Bloodlust,
  },
  {
    id: 142,
    name: 'Aenain',
    classId: Classes.Elementalist,
    specialtySpell: Spells.DisruptingRay,
  },
  {
    id: 143,
    name: 'Gelare',
    classId: Classes.Elementalist,
  },
  {
    id: 144,
    name: 'Grindan',
    classId: Classes.Elementalist,
  },
  {
    id: 145,
    name: 'Cassiopeia',
    classId: Classes.Captain,
    specialtyUnit: [Creatures.Nymph, Creatures.Oceanid],
  },
  {
    id: 146,
    name: 'Corkes',
    classId: Classes.Captain,
    specialtySkill: SecondarySkills.Offense,
  },
  {
    id: 147,
    name: 'Jeremy',
    classId: Classes.Captain,
    specialtyUnit: [Creatures.Cannon],
  },
  {
    id: 148,
    name: 'Illor',
    classId: Classes.Captain,
    specialtyUnit: [Creatures.Stormbird, Creatures.Ayssid],
  },
  {
    id: 149,
    name: 'Derek',
    classId: Classes.Captain,
    specialtyUnit: [Creatures.CrewMate, Creatures.Seaman],
  },
  {
    id: 150,
    name: 'Leena',
    classId: Classes.Captain,
  },
  {
    id: 151,
    name: 'Anabel',
    classId: Classes.Captain,
    specialtyUnit: [Creatures.Pirate, Creatures.Corsair, Creatures.Pirate],
  },
  {
    id: 152,
    name: 'Miriam',
    classId: Classes.Captain,
  },
  {
    id: 153,
    name: 'Casmetra',
    classId: Classes.Navigator,
    specialtyUnit: [Creatures.SeaWitch, Creatures.Sorceress],
  },
  {
    id: 154,
    name: 'Eovacius',
    classId: Classes.Navigator,
  },
  {
    id: 155,
    name: 'Spint',
    classId: Classes.Navigator,
    specialtySkill: SecondarySkills.Sorcery,
  },
  {
    id: 156,
    name: 'Andal',
    classId: Classes.Navigator,
  },
  {
    id: 157,
    name: 'Manfred',
    classId: Classes.Navigator,
    specialtySpell: Spells.Fireball,
  },
  {
    id: 158,
    name: 'Zilare',
    classId: Classes.Navigator,
  },
  {
    id: 159,
    name: 'Astra',
    classId: Classes.Navigator,
  },
  {
    id: 160,
    name: 'Dargem',
    classId: Classes.Navigator,
  },
  {
    id: 161,
    name: 'Giselle',
    classId: Classes.Ranger,
  },
]
